// Code generated by ogen, DO NOT EDIT.

package adminapi

// OperationName is the ogen operation name
type OperationName = string

const (
	ControlRebalanceOperation   OperationName = "ControlRebalance"
	CreateAccessKeyOperation    OperationName = "CreateAccessKey"
	DeleteAccessKeyOperation    OperationName = "DeleteAccessKey"
	GetClusterStatusOperation   OperationName = "GetClusterStatus"
	GetInfoOperation            OperationName = "GetInfo"
	GetRebalanceStatusOperation OperationName = "GetRebalanceStatus"
	ListAccessKeysOperation     OperationName = "ListAccessKeys"
)
