// Code generated by ogen, DO NOT EDIT.

package adminapi

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// ControlRebalance implements controlRebalance operation.
//
// Start, pause or resume the cluster-wide rebalance from this node. At most one rebalance runs
// cluster-wide (etcd election); starting on several nodes leaves the extras waiting as standby
// runners. Pausing stops this node's runner and keeps the resume cursor, so a later start/resume —
// on any node — continues where it left off.
//
// POST /api/v1/cluster/rebalance
func (UnimplementedHandler) ControlRebalance(ctx context.Context, req *RebalanceControlRequest) (r *RebalanceStatus, _ error) {
	return r, ht.ErrNotImplemented
}

// CreateAccessKey implements createAccessKey operation.
//
// Create a runtime credential. The access key and secret are generated when not supplied. The secret
// is returned only in this response and cannot be retrieved later.
//
// POST /api/v1/access-keys
func (UnimplementedHandler) CreateAccessKey(ctx context.Context, req *CreateAccessKeyRequest) (r *CreatedAccessKey, _ error) {
	return r, ht.ErrNotImplemented
}

// DeleteAccessKey implements deleteAccessKey operation.
//
// Remove a runtime credential. Config-defined credentials cannot be deleted.
//
// DELETE /api/v1/access-keys/{accessKey}
func (UnimplementedHandler) DeleteAccessKey(ctx context.Context, params DeleteAccessKeyParams) error {
	return ht.ErrNotImplemented
}

// GetClusterStatus implements getClusterStatus operation.
//
// Cluster-wide view read from the control plane: the agreed schema version, every node with its disks
// and reported capacity, aggregate capacity, placement skew and whether a rebalance is currently
// running. State is "disabled" when the server is not in cluster mode.
//
// GET /api/v1/cluster/status
func (UnimplementedHandler) GetClusterStatus(ctx context.Context) (r *ClusterStatus, _ error) {
	return r, ht.ErrNotImplemented
}

// GetInfo implements getInfo operation.
//
// Build information, uptime and whether authentication is enabled.
//
// GET /api/v1/info
func (UnimplementedHandler) GetInfo(ctx context.Context) (r *InstanceInfo, _ error) {
	return r, ht.ErrNotImplemented
}

// GetRebalanceStatus implements getRebalanceStatus operation.
//
// State and progress of the cluster rebalance runner on this node, the persisted resume cursor and the
// depth of the async repair queue. State is "disabled" when the server is not in cluster mode.
//
// GET /api/v1/cluster/rebalance
func (UnimplementedHandler) GetRebalanceStatus(ctx context.Context) (r *RebalanceStatus, _ error) {
	return r, ht.ErrNotImplemented
}

// ListAccessKeys implements listAccessKeys operation.
//
// Every credential the server accepts, secrets omitted.
//
// GET /api/v1/access-keys
func (UnimplementedHandler) ListAccessKeys(ctx context.Context) (r *AccessKeyList, _ error) {
	return r, ht.ErrNotImplemented
}

// NewError creates *ErrorStatusCode from error returned by handler.
//
// Used for common default response.
func (UnimplementedHandler) NewError(ctx context.Context, err error) (r *ErrorStatusCode) {
	r = new(ErrorStatusCode)
	return r
}
