// Code generated by ogen, DO NOT EDIT.

package adminapi

// OperationName is the ogen operation name
type OperationName = string

const (
	CreateAccessKeyOperation OperationName = "CreateAccessKey"
	DeleteAccessKeyOperation OperationName = "DeleteAccessKey"
	GetInfoOperation         OperationName = "GetInfo"
	ListAccessKeysOperation  OperationName = "ListAccessKeys"
)
