// Code generated by ogen, DO NOT EDIT.

package adminapi

import (
	"context"
)

// Handler handles operations described by OpenAPI v3 specification.
type Handler interface {
	// ApplyLayout implements applyLayout operation.
	//
	// Compute the next layout from the full set of member roles and adopt it on this node; gossip carries
	// it to every other node. Slots keep their node wherever it is still valid, so only the data that has
	// to move does. With dry_run the computed layout and the number of slots that would move are returned
	// without adopting anything. Returns 400 when the roles cannot produce a layout, e.g. fewer members
	// with capacity than the widest width.
	//
	// POST /api/v1/cluster/layout
	ApplyLayout(ctx context.Context, req *ApplyLayoutRequest, params ApplyLayoutParams) (*LayoutChange, error)
	// CreateAccessKey implements createAccessKey operation.
	//
	// Create a runtime credential. The access key and secret are generated when not supplied. The secret
	// is returned only in this response and cannot be retrieved later.
	//
	// POST /api/v1/access-keys
	CreateAccessKey(ctx context.Context, req *CreateAccessKeyRequest) (*CreatedAccessKey, error)
	// DeleteAccessKey implements deleteAccessKey operation.
	//
	// Remove a runtime credential. Config-defined credentials cannot be deleted.
	//
	// DELETE /api/v1/access-keys/{accessKey}
	DeleteAccessKey(ctx context.Context, params DeleteAccessKeyParams) error
	// GetInfo implements getInfo operation.
	//
	// Build information, uptime and whether authentication is enabled.
	//
	// GET /api/v1/info
	GetInfo(ctx context.Context) (*InstanceInfo, error)
	// GetLayout implements getLayout operation.
	//
	// The layout this node has adopted: version, partitions, the widths it spreads for, each member's role
	// and share of slots, and how many slots a single zone or rack holds per width. Returns 501 when
	// cluster mode is off and 404 before any layout has been applied.
	//
	// GET /api/v1/cluster/layout
	GetLayout(ctx context.Context) (*Layout, error)
	// ListAccessKeys implements listAccessKeys operation.
	//
	// Every credential the server accepts, secrets omitted.
	//
	// GET /api/v1/access-keys
	ListAccessKeys(ctx context.Context) (*AccessKeyList, error)
	// ListClusterNodes implements listClusterNodes operation.
	//
	// This node and every peer it gossips with: address, the layout version each last reported, and
	// whether the last exchange succeeded. Returns 501 when cluster mode is off.
	//
	// GET /api/v1/cluster/nodes
	ListClusterNodes(ctx context.Context) (*ClusterNodeList, error)
	// ReloadConfig implements reloadConfig operation.
	//
	// Re-read the configuration file and apply the parts that change without a restart — the
	// config-defined credentials and grants, the anonymously readable buckets and the TLS certificate —
	// exactly as SIGHUP does. Runtime credentials created through this API are preserved. Returns what was
	// reloaded and the config revision now in effect, so an orchestrator can confirm a config change
	// landed without shelling into the process.
	//
	// POST /api/v1/reload
	ReloadConfig(ctx context.Context) (*ReloadResult, error)
	// RotateEncryptionKeys implements rotateEncryptionKeys operation.
	//
	// Rewrap the data key of every encrypted object version and in-flight upload under the current master
	// key (encryption.master_key_file). Only the keys are rewritten, never object data. Safe to interrupt
	// and run again: keys already current are skipped. A previous master key can be removed from
	// encryption.previous_key_files once a run reports remaining 0. In a cluster, every node must already
	// have the new key as current and the old one as previous; one run covers the cluster. Returns 501
	// when no master key is configured.
	//
	// POST /api/v1/encryption/rotate
	RotateEncryptionKeys(ctx context.Context) (*RotateResult, error)
	// NewError creates *ErrorStatusCode from error returned by handler.
	//
	// Used for common default response.
	NewError(ctx context.Context, err error) *ErrorStatusCode
}

// Server implements http server based on OpenAPI v3 specification and
// calls Handler to handle requests.
type Server struct {
	h Handler
	baseServer
}

// NewServer creates new Server.
func NewServer(h Handler, opts ...ServerOption) (*Server, error) {
	s, err := newServerConfig(opts...).baseServer()
	if err != nil {
		return nil, err
	}
	return &Server{
		h:          h,
		baseServer: s,
	}, nil
}
