// Code generated by ogen, DO NOT EDIT.

package adminapi

import (
	"net/http"
	"net/url"

	"github.com/go-faster/errors"
	"github.com/ogen-go/ogen/conv"
	"github.com/ogen-go/ogen/middleware"
	"github.com/ogen-go/ogen/ogenerrors"
	"github.com/ogen-go/ogen/uri"
	"github.com/ogen-go/ogen/validate"
)

// DeleteAccessKeyParams is parameters of deleteAccessKey operation.
type DeleteAccessKeyParams struct {
	// The access key ID to delete.
	AccessKey string
}

func unpackDeleteAccessKeyParams(packed middleware.Parameters) (params DeleteAccessKeyParams) {
	{
		key := middleware.ParameterKey{
			Name: "accessKey",
			In:   "path",
		}
		params.AccessKey = packed[key].(string)
	}
	return params
}

func decodeDeleteAccessKeyParams(args [1]string, argsEscaped bool, r *http.Request) (params DeleteAccessKeyParams, _ error) {
	// Decode path: accessKey.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "accessKey",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToString(val)
				if err != nil {
					return err
				}

				params.AccessKey = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "accessKey",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}

// GetBucketSchemeParams is parameters of getBucketScheme operation.
type GetBucketSchemeParams struct {
	// The bucket name.
	Bucket string
}

func unpackGetBucketSchemeParams(packed middleware.Parameters) (params GetBucketSchemeParams) {
	{
		key := middleware.ParameterKey{
			Name: "bucket",
			In:   "path",
		}
		params.Bucket = packed[key].(string)
	}
	return params
}

func decodeGetBucketSchemeParams(args [1]string, argsEscaped bool, r *http.Request) (params GetBucketSchemeParams, _ error) {
	// Decode path: bucket.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "bucket",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToString(val)
				if err != nil {
					return err
				}

				params.Bucket = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "bucket",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}

// SetBucketSchemeParams is parameters of setBucketScheme operation.
type SetBucketSchemeParams struct {
	// The bucket name.
	Bucket string
}

func unpackSetBucketSchemeParams(packed middleware.Parameters) (params SetBucketSchemeParams) {
	{
		key := middleware.ParameterKey{
			Name: "bucket",
			In:   "path",
		}
		params.Bucket = packed[key].(string)
	}
	return params
}

func decodeSetBucketSchemeParams(args [1]string, argsEscaped bool, r *http.Request) (params SetBucketSchemeParams, _ error) {
	// Decode path: bucket.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "bucket",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToString(val)
				if err != nil {
					return err
				}

				params.Bucket = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "bucket",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}
