// Code generated by ogen, DO NOT EDIT.

package adminapi

import (
	"net/http"
	"net/url"

	"github.com/go-faster/errors"
	"github.com/ogen-go/ogen/conv"
	"github.com/ogen-go/ogen/middleware"
	"github.com/ogen-go/ogen/ogenerrors"
	"github.com/ogen-go/ogen/uri"
	"github.com/ogen-go/ogen/validate"
)

// ApplyLayoutParams is parameters of applyLayout operation.
type ApplyLayoutParams struct {
	DryRun OptBool `json:",omitempty,omitzero"`
}

func unpackApplyLayoutParams(packed middleware.Parameters) (params ApplyLayoutParams) {
	{
		key := middleware.ParameterKey{
			Name: "dry_run",
			In:   "query",
		}
		if v, ok := packed[key]; ok {
			params.DryRun = v.(OptBool)
		}
	}
	return params
}

func decodeApplyLayoutParams(args [0]string, argsEscaped bool, r *http.Request) (params ApplyLayoutParams, _ error) {
	q := uri.NewQueryDecoder(r.URL.Query())
	// Set default value for query: dry_run.
	{
		val := bool(false)
		params.DryRun.SetTo(val)
	}
	// Decode query: dry_run.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "dry_run",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				var paramsDotDryRunVal bool
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToBool(val)
					if err != nil {
						return err
					}

					paramsDotDryRunVal = c
					return nil
				}(); err != nil {
					return err
				}
				params.DryRun.SetTo(paramsDotDryRunVal)
				return nil
			}); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "dry_run",
			In:   "query",
			Err:  err,
		}
	}
	return params, nil
}

// DeleteAccessKeyParams is parameters of deleteAccessKey operation.
type DeleteAccessKeyParams struct {
	// The access key ID to delete.
	AccessKey string
}

func unpackDeleteAccessKeyParams(packed middleware.Parameters) (params DeleteAccessKeyParams) {
	{
		key := middleware.ParameterKey{
			Name: "accessKey",
			In:   "path",
		}
		params.AccessKey = packed[key].(string)
	}
	return params
}

func decodeDeleteAccessKeyParams(args [1]string, argsEscaped bool, r *http.Request) (params DeleteAccessKeyParams, _ error) {
	// Decode path: accessKey.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "accessKey",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToString(val)
				if err != nil {
					return err
				}

				params.AccessKey = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "accessKey",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}
