// Code generated by ogen, DO NOT EDIT.

package adminapi

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// ApplyLayout implements applyLayout operation.
//
// Compute the next layout from the full set of member roles and adopt it on this node; gossip carries
// it to every other node. Slots keep their node wherever it is still valid, so only the data that has
// to move does. The answer carries the versions the change retains, as a read right after would; a
// node they place data on is still serving it. With dry_run the computed layout and the number of
// slots that would move are returned without adopting anything. Returns 400 when the roles cannot
// produce a layout, e.g. fewer members with capacity than the widest width.
//
// POST /api/v1/cluster/layout
func (UnimplementedHandler) ApplyLayout(ctx context.Context, req *ApplyLayoutRequest, params ApplyLayoutParams) (r *LayoutChange, _ error) {
	return r, ht.ErrNotImplemented
}

// CreateAccessKey implements createAccessKey operation.
//
// Create a runtime credential. The access key and secret are generated when not supplied. The secret
// is returned only in this response and cannot be retrieved later.
//
// POST /api/v1/access-keys
func (UnimplementedHandler) CreateAccessKey(ctx context.Context, req *CreateAccessKeyRequest) (r *CreatedAccessKey, _ error) {
	return r, ht.ErrNotImplemented
}

// DeleteAccessKey implements deleteAccessKey operation.
//
// Remove a runtime credential. Config-defined credentials cannot be deleted.
//
// DELETE /api/v1/access-keys/{accessKey}
func (UnimplementedHandler) DeleteAccessKey(ctx context.Context, params DeleteAccessKeyParams) error {
	return ht.ErrNotImplemented
}

// GetBucketScheme implements getBucketScheme operation.
//
// "rf3" (three replicas, the default) or "ec:K,M" (erasure coded as K data and M parity shards).
// Returns 404 for a missing bucket.
//
// GET /api/v1/buckets/{bucket}/scheme
func (UnimplementedHandler) GetBucketScheme(ctx context.Context, params GetBucketSchemeParams) (r *BucketScheme, _ error) {
	return r, ht.ErrNotImplemented
}

// GetInfo implements getInfo operation.
//
// Build information, uptime and whether authentication is enabled.
//
// GET /api/v1/info
func (UnimplementedHandler) GetInfo(ctx context.Context) (r *InstanceInfo, _ error) {
	return r, ht.ErrNotImplemented
}

// GetLayout implements getLayout operation.
//
// The layout this node has adopted: version, partitions, the widths it spreads for, each member's role
// and share of slots, and how many slots a single zone or rack holds per width. Returns 501 when
// cluster mode is off and 404 before any layout has been applied.
//
// GET /api/v1/cluster/layout
func (UnimplementedHandler) GetLayout(ctx context.Context) (r *Layout, _ error) {
	return r, ht.ErrNotImplemented
}

// ListAccessKeys implements listAccessKeys operation.
//
// Every credential the server accepts, secrets omitted.
//
// GET /api/v1/access-keys
func (UnimplementedHandler) ListAccessKeys(ctx context.Context) (r *AccessKeyList, _ error) {
	return r, ht.ErrNotImplemented
}

// ListClusterNodes implements listClusterNodes operation.
//
// This node and every peer it gossips with: address, the layout version each last reported, and
// whether the last exchange succeeded. Returns 501 when cluster mode is off.
//
// GET /api/v1/cluster/nodes
func (UnimplementedHandler) ListClusterNodes(ctx context.Context) (r *ClusterNodeList, _ error) {
	return r, ht.ErrNotImplemented
}

// ReloadConfig implements reloadConfig operation.
//
// Re-read the configuration file and apply the parts that change without a restart — the
// config-defined credentials and grants, the anonymously readable buckets and the TLS certificate —
// exactly as SIGHUP does. Runtime credentials created through this API are preserved. Returns what was
// reloaded and the config revision now in effect, so an orchestrator can confirm a config change
// landed without shelling into the process.
//
// POST /api/v1/reload
func (UnimplementedHandler) ReloadConfig(ctx context.Context) (r *ReloadResult, _ error) {
	return r, ht.ErrNotImplemented
}

// RotateEncryptionKeys implements rotateEncryptionKeys operation.
//
// Rewrap the data key of every encrypted object version and in-flight upload under the current master
// key (encryption.master_key_file). Only the keys are rewritten, never object data. Safe to interrupt
// and run again: keys already current are skipped. A previous master key can be removed from
// encryption.previous_key_files once a run reports remaining 0. In a cluster, every node must already
// have the new key as current and the old one as previous; one run covers the cluster. Returns 501
// when no master key is configured.
//
// POST /api/v1/encryption/rotate
func (UnimplementedHandler) RotateEncryptionKeys(ctx context.Context) (r *RotateResult, _ error) {
	return r, ht.ErrNotImplemented
}

// SetBucketScheme implements setBucketScheme operation.
//
// Applies to blocks written from now on; existing ones keep the scheme they were written with. Blocks
// below 256 KiB and small inline objects stay replicated. A coded scheme needs a cluster layout spread
// for width K+M (fs layout apply with that width), so that every shard lands on its own node; it is
// refused with 400 otherwise, and on a single node.
//
// PUT /api/v1/buckets/{bucket}/scheme
func (UnimplementedHandler) SetBucketScheme(ctx context.Context, req *BucketScheme, params SetBucketSchemeParams) (r *BucketScheme, _ error) {
	return r, ht.ErrNotImplemented
}

// SkipClusterNode implements skipClusterNode operation.
//
// Record the node as synced through the current layout version, so older versions can retire without
// it. For a node that is gone for good and blocks a layout change from completing: whatever only it
// held is given up. Gossip carries the release to every node. Returns 501 when cluster mode is off.
//
// POST /api/v1/cluster/nodes/{id}/skip
func (UnimplementedHandler) SkipClusterNode(ctx context.Context, params SkipClusterNodeParams) error {
	return ht.ErrNotImplemented
}

// NewError creates *ErrorStatusCode from error returned by handler.
//
// Used for common default response.
func (UnimplementedHandler) NewError(ctx context.Context, err error) (r *ErrorStatusCode) {
	r = new(ErrorStatusCode)
	return r
}
