// Code generated by ogen, DO NOT EDIT.

package adminapi

// OperationName is the ogen operation name
type OperationName = string

const (
	ApplyMigrationsOperation      OperationName = "ApplyMigrations"
	ControlRebalanceOperation     OperationName = "ControlRebalance"
	CreateAccessKeyOperation      OperationName = "CreateAccessKey"
	DeleteAccessKeyOperation      OperationName = "DeleteAccessKey"
	GetBucketSchemeOperation      OperationName = "GetBucketScheme"
	GetBucketUsageOperation       OperationName = "GetBucketUsage"
	GetClusterStatusOperation     OperationName = "GetClusterStatus"
	GetInfoOperation              OperationName = "GetInfo"
	GetMigrationStatusOperation   OperationName = "GetMigrationStatus"
	GetPublicReadBucketsOperation OperationName = "GetPublicReadBuckets"
	GetRebalanceStatusOperation   OperationName = "GetRebalanceStatus"
	ListAccessKeysOperation       OperationName = "ListAccessKeys"
	ReloadConfigOperation         OperationName = "ReloadConfig"
	SetBucketSchemeOperation      OperationName = "SetBucketScheme"
	SetPublicReadBucketsOperation OperationName = "SetPublicReadBuckets"
)
