// Code generated by ogen, DO NOT EDIT.

package adminapi

import (
	"fmt"
	"time"

	"github.com/go-faster/errors"
)

func (s *ErrorStatusCode) Error() string {
	return fmt.Sprintf("code %d: %+v", s.StatusCode, s.Response)
}

// Ref: #/components/schemas/AccessKey
type AccessKey struct {
	AccessKey string  `json:"access_key"`
	Grants    []Grant `json:"grants"`
	Source    Source  `json:"source"`
	// Creation time, for runtime-managed credentials.
	CreatedAt OptDateTime `json:"created_at"`
}

// GetAccessKey returns the value of AccessKey.
func (s *AccessKey) GetAccessKey() string {
	return s.AccessKey
}

// GetGrants returns the value of Grants.
func (s *AccessKey) GetGrants() []Grant {
	return s.Grants
}

// GetSource returns the value of Source.
func (s *AccessKey) GetSource() Source {
	return s.Source
}

// GetCreatedAt returns the value of CreatedAt.
func (s *AccessKey) GetCreatedAt() OptDateTime {
	return s.CreatedAt
}

// SetAccessKey sets the value of AccessKey.
func (s *AccessKey) SetAccessKey(val string) {
	s.AccessKey = val
}

// SetGrants sets the value of Grants.
func (s *AccessKey) SetGrants(val []Grant) {
	s.Grants = val
}

// SetSource sets the value of Source.
func (s *AccessKey) SetSource(val Source) {
	s.Source = val
}

// SetCreatedAt sets the value of CreatedAt.
func (s *AccessKey) SetCreatedAt(val OptDateTime) {
	s.CreatedAt = val
}

// Ref: #/components/schemas/AccessKeyList
type AccessKeyList struct {
	Keys []AccessKey `json:"keys"`
}

// GetKeys returns the value of Keys.
func (s *AccessKeyList) GetKeys() []AccessKey {
	return s.Keys
}

// SetKeys sets the value of Keys.
func (s *AccessKeyList) SetKeys(val []AccessKey) {
	s.Keys = val
}

// Ref: #/components/schemas/ApplyLayoutRequest
type ApplyLayoutRequest struct {
	Members []LayoutRole `json:"members"`
	// Slot prefixes to spread for: 3 for replicated data, k+m per erasure scheme. Default: the current
	// layout's, else [3].
	Widths []int `json:"widths"`
	// Partition count, a power of two. Only used for the first layout; default 256.
	Partitions OptInt `json:"partitions"`
}

// GetMembers returns the value of Members.
func (s *ApplyLayoutRequest) GetMembers() []LayoutRole {
	return s.Members
}

// GetWidths returns the value of Widths.
func (s *ApplyLayoutRequest) GetWidths() []int {
	return s.Widths
}

// GetPartitions returns the value of Partitions.
func (s *ApplyLayoutRequest) GetPartitions() OptInt {
	return s.Partitions
}

// SetMembers sets the value of Members.
func (s *ApplyLayoutRequest) SetMembers(val []LayoutRole) {
	s.Members = val
}

// SetWidths sets the value of Widths.
func (s *ApplyLayoutRequest) SetWidths(val []int) {
	s.Widths = val
}

// SetPartitions sets the value of Partitions.
func (s *ApplyLayoutRequest) SetPartitions(val OptInt) {
	s.Partitions = val
}

// Ref: #/components/schemas/ClusterNode
type ClusterNode struct {
	ID   OptString `json:"id"`
	Addr string    `json:"addr"`
	Self bool      `json:"self"`
	// The last exchange with this peer succeeded. Always true for this node.
	Up            bool        `json:"up"`
	LayoutVersion OptUint64   `json:"layout_version"`
	LastSeen      OptDateTime `json:"last_seen"`
	Error         OptString   `json:"error"`
}

// GetID returns the value of ID.
func (s *ClusterNode) GetID() OptString {
	return s.ID
}

// GetAddr returns the value of Addr.
func (s *ClusterNode) GetAddr() string {
	return s.Addr
}

// GetSelf returns the value of Self.
func (s *ClusterNode) GetSelf() bool {
	return s.Self
}

// GetUp returns the value of Up.
func (s *ClusterNode) GetUp() bool {
	return s.Up
}

// GetLayoutVersion returns the value of LayoutVersion.
func (s *ClusterNode) GetLayoutVersion() OptUint64 {
	return s.LayoutVersion
}

// GetLastSeen returns the value of LastSeen.
func (s *ClusterNode) GetLastSeen() OptDateTime {
	return s.LastSeen
}

// GetError returns the value of Error.
func (s *ClusterNode) GetError() OptString {
	return s.Error
}

// SetID sets the value of ID.
func (s *ClusterNode) SetID(val OptString) {
	s.ID = val
}

// SetAddr sets the value of Addr.
func (s *ClusterNode) SetAddr(val string) {
	s.Addr = val
}

// SetSelf sets the value of Self.
func (s *ClusterNode) SetSelf(val bool) {
	s.Self = val
}

// SetUp sets the value of Up.
func (s *ClusterNode) SetUp(val bool) {
	s.Up = val
}

// SetLayoutVersion sets the value of LayoutVersion.
func (s *ClusterNode) SetLayoutVersion(val OptUint64) {
	s.LayoutVersion = val
}

// SetLastSeen sets the value of LastSeen.
func (s *ClusterNode) SetLastSeen(val OptDateTime) {
	s.LastSeen = val
}

// SetError sets the value of Error.
func (s *ClusterNode) SetError(val OptString) {
	s.Error = val
}

// Ref: #/components/schemas/ClusterNodeList
type ClusterNodeList struct {
	Nodes []ClusterNode `json:"nodes"`
}

// GetNodes returns the value of Nodes.
func (s *ClusterNodeList) GetNodes() []ClusterNode {
	return s.Nodes
}

// SetNodes sets the value of Nodes.
func (s *ClusterNodeList) SetNodes(val []ClusterNode) {
	s.Nodes = val
}

// Ref: #/components/schemas/CreateAccessKeyRequest
type CreateAccessKeyRequest struct {
	// Access key ID; generated when omitted.
	AccessKey OptString `json:"access_key"`
	// Secret access key; generated when omitted.
	SecretKey OptString `json:"secret_key"`
	Grants    []Grant   `json:"grants"`
}

// GetAccessKey returns the value of AccessKey.
func (s *CreateAccessKeyRequest) GetAccessKey() OptString {
	return s.AccessKey
}

// GetSecretKey returns the value of SecretKey.
func (s *CreateAccessKeyRequest) GetSecretKey() OptString {
	return s.SecretKey
}

// GetGrants returns the value of Grants.
func (s *CreateAccessKeyRequest) GetGrants() []Grant {
	return s.Grants
}

// SetAccessKey sets the value of AccessKey.
func (s *CreateAccessKeyRequest) SetAccessKey(val OptString) {
	s.AccessKey = val
}

// SetSecretKey sets the value of SecretKey.
func (s *CreateAccessKeyRequest) SetSecretKey(val OptString) {
	s.SecretKey = val
}

// SetGrants sets the value of Grants.
func (s *CreateAccessKeyRequest) SetGrants(val []Grant) {
	s.Grants = val
}

// Ref: #/components/schemas/CreatedAccessKey
type CreatedAccessKey struct {
	AccessKey string `json:"access_key"`
	// Secret access key — shown once, not retrievable later.
	SecretKey string    `json:"secret_key"`
	Grants    []Grant   `json:"grants"`
	CreatedAt time.Time `json:"created_at"`
}

// GetAccessKey returns the value of AccessKey.
func (s *CreatedAccessKey) GetAccessKey() string {
	return s.AccessKey
}

// GetSecretKey returns the value of SecretKey.
func (s *CreatedAccessKey) GetSecretKey() string {
	return s.SecretKey
}

// GetGrants returns the value of Grants.
func (s *CreatedAccessKey) GetGrants() []Grant {
	return s.Grants
}

// GetCreatedAt returns the value of CreatedAt.
func (s *CreatedAccessKey) GetCreatedAt() time.Time {
	return s.CreatedAt
}

// SetAccessKey sets the value of AccessKey.
func (s *CreatedAccessKey) SetAccessKey(val string) {
	s.AccessKey = val
}

// SetSecretKey sets the value of SecretKey.
func (s *CreatedAccessKey) SetSecretKey(val string) {
	s.SecretKey = val
}

// SetGrants sets the value of Grants.
func (s *CreatedAccessKey) SetGrants(val []Grant) {
	s.Grants = val
}

// SetCreatedAt sets the value of CreatedAt.
func (s *CreatedAccessKey) SetCreatedAt(val time.Time) {
	s.CreatedAt = val
}

// DeleteAccessKeyNoContent is response for DeleteAccessKey operation.
type DeleteAccessKeyNoContent struct{}

// Error occurred while processing request.
// Ref: #/components/schemas/Error
type Error struct {
	ErrorMessage string `json:"error_message"`
}

// GetErrorMessage returns the value of ErrorMessage.
func (s *Error) GetErrorMessage() string {
	return s.ErrorMessage
}

// SetErrorMessage sets the value of ErrorMessage.
func (s *Error) SetErrorMessage(val string) {
	s.ErrorMessage = val
}

// ErrorStatusCode wraps Error with StatusCode.
type ErrorStatusCode struct {
	StatusCode int
	Response   Error
}

// GetStatusCode returns the value of StatusCode.
func (s *ErrorStatusCode) GetStatusCode() int {
	return s.StatusCode
}

// GetResponse returns the value of Response.
func (s *ErrorStatusCode) GetResponse() Error {
	return s.Response
}

// SetStatusCode sets the value of StatusCode.
func (s *ErrorStatusCode) SetStatusCode(val int) {
	s.StatusCode = val
}

// SetResponse sets the value of Response.
func (s *ErrorStatusCode) SetResponse(val Error) {
	s.Response = val
}

// Ref: #/components/schemas/Grant
type Grant struct {
	// Bucket glob pattern; "*" matches all buckets.
	Bucket     string     `json:"bucket"`
	Permission Permission `json:"permission"`
}

// GetBucket returns the value of Bucket.
func (s *Grant) GetBucket() string {
	return s.Bucket
}

// GetPermission returns the value of Permission.
func (s *Grant) GetPermission() Permission {
	return s.Permission
}

// SetBucket sets the value of Bucket.
func (s *Grant) SetBucket(val string) {
	s.Bucket = val
}

// SetPermission sets the value of Permission.
func (s *Grant) SetPermission(val Permission) {
	s.Permission = val
}

// Ref: #/components/schemas/InstanceInfo
type InstanceInfo struct {
	Version       string    `json:"version"`
	Commit        string    `json:"commit"`
	GoVersion     string    `json:"go_version"`
	Os            string    `json:"os"`
	Arch          string    `json:"arch"`
	StartTime     time.Time `json:"start_time"`
	UptimeSeconds float64   `json:"uptime_seconds"`
	// Whether SigV4 authentication is enabled.
	AuthEnabled bool `json:"auth_enabled"`
	// Opaque marker echoed from the loaded config file's "revision" field, updated on reload. Empty when
	// the config sets none. An orchestrator writes a revision into each node's config and reads it back
	// here to confirm the node has applied that revision.
	ConfigRevision OptString `json:"config_revision"`
}

// GetVersion returns the value of Version.
func (s *InstanceInfo) GetVersion() string {
	return s.Version
}

// GetCommit returns the value of Commit.
func (s *InstanceInfo) GetCommit() string {
	return s.Commit
}

// GetGoVersion returns the value of GoVersion.
func (s *InstanceInfo) GetGoVersion() string {
	return s.GoVersion
}

// GetOs returns the value of Os.
func (s *InstanceInfo) GetOs() string {
	return s.Os
}

// GetArch returns the value of Arch.
func (s *InstanceInfo) GetArch() string {
	return s.Arch
}

// GetStartTime returns the value of StartTime.
func (s *InstanceInfo) GetStartTime() time.Time {
	return s.StartTime
}

// GetUptimeSeconds returns the value of UptimeSeconds.
func (s *InstanceInfo) GetUptimeSeconds() float64 {
	return s.UptimeSeconds
}

// GetAuthEnabled returns the value of AuthEnabled.
func (s *InstanceInfo) GetAuthEnabled() bool {
	return s.AuthEnabled
}

// GetConfigRevision returns the value of ConfigRevision.
func (s *InstanceInfo) GetConfigRevision() OptString {
	return s.ConfigRevision
}

// SetVersion sets the value of Version.
func (s *InstanceInfo) SetVersion(val string) {
	s.Version = val
}

// SetCommit sets the value of Commit.
func (s *InstanceInfo) SetCommit(val string) {
	s.Commit = val
}

// SetGoVersion sets the value of GoVersion.
func (s *InstanceInfo) SetGoVersion(val string) {
	s.GoVersion = val
}

// SetOs sets the value of Os.
func (s *InstanceInfo) SetOs(val string) {
	s.Os = val
}

// SetArch sets the value of Arch.
func (s *InstanceInfo) SetArch(val string) {
	s.Arch = val
}

// SetStartTime sets the value of StartTime.
func (s *InstanceInfo) SetStartTime(val time.Time) {
	s.StartTime = val
}

// SetUptimeSeconds sets the value of UptimeSeconds.
func (s *InstanceInfo) SetUptimeSeconds(val float64) {
	s.UptimeSeconds = val
}

// SetAuthEnabled sets the value of AuthEnabled.
func (s *InstanceInfo) SetAuthEnabled(val bool) {
	s.AuthEnabled = val
}

// SetConfigRevision sets the value of ConfigRevision.
func (s *InstanceInfo) SetConfigRevision(val OptString) {
	s.ConfigRevision = val
}

// Ref: #/components/schemas/Layout
type Layout struct {
	Version    uint64         `json:"version"`
	Partitions int            `json:"partitions"`
	Widths     []int          `json:"widths"`
	Members    []LayoutMember `json:"members"`
	Spread     []LayoutSpread `json:"spread"`
}

// GetVersion returns the value of Version.
func (s *Layout) GetVersion() uint64 {
	return s.Version
}

// GetPartitions returns the value of Partitions.
func (s *Layout) GetPartitions() int {
	return s.Partitions
}

// GetWidths returns the value of Widths.
func (s *Layout) GetWidths() []int {
	return s.Widths
}

// GetMembers returns the value of Members.
func (s *Layout) GetMembers() []LayoutMember {
	return s.Members
}

// GetSpread returns the value of Spread.
func (s *Layout) GetSpread() []LayoutSpread {
	return s.Spread
}

// SetVersion sets the value of Version.
func (s *Layout) SetVersion(val uint64) {
	s.Version = val
}

// SetPartitions sets the value of Partitions.
func (s *Layout) SetPartitions(val int) {
	s.Partitions = val
}

// SetWidths sets the value of Widths.
func (s *Layout) SetWidths(val []int) {
	s.Widths = val
}

// SetMembers sets the value of Members.
func (s *Layout) SetMembers(val []LayoutMember) {
	s.Members = val
}

// SetSpread sets the value of Spread.
func (s *Layout) SetSpread(val []LayoutSpread) {
	s.Spread = val
}

// Ref: #/components/schemas/LayoutChange
type LayoutChange struct {
	Layout Layout `json:"layout"`
	// Slots whose node differs from the current layout.
	MovedSlots int  `json:"moved_slots"`
	Applied    bool `json:"applied"`
}

// GetLayout returns the value of Layout.
func (s *LayoutChange) GetLayout() Layout {
	return s.Layout
}

// GetMovedSlots returns the value of MovedSlots.
func (s *LayoutChange) GetMovedSlots() int {
	return s.MovedSlots
}

// GetApplied returns the value of Applied.
func (s *LayoutChange) GetApplied() bool {
	return s.Applied
}

// SetLayout sets the value of Layout.
func (s *LayoutChange) SetLayout(val Layout) {
	s.Layout = val
}

// SetMovedSlots sets the value of MovedSlots.
func (s *LayoutChange) SetMovedSlots(val int) {
	s.MovedSlots = val
}

// SetApplied sets the value of Applied.
func (s *LayoutChange) SetApplied(val bool) {
	s.Applied = val
}

// Merged schema.
// Ref: #/components/schemas/LayoutMember
type LayoutMember struct {
	ID   string    `json:"id"`
	Zone OptString `json:"zone"`
	Rack OptString `json:"rack"`
	// Bytes of data the node takes. Zero makes it a gateway that holds no slots.
	Capacity uint64 `json:"capacity"`
	// Slots this member holds.
	Slots int `json:"slots"`
}

// GetID returns the value of ID.
func (s *LayoutMember) GetID() string {
	return s.ID
}

// GetZone returns the value of Zone.
func (s *LayoutMember) GetZone() OptString {
	return s.Zone
}

// GetRack returns the value of Rack.
func (s *LayoutMember) GetRack() OptString {
	return s.Rack
}

// GetCapacity returns the value of Capacity.
func (s *LayoutMember) GetCapacity() uint64 {
	return s.Capacity
}

// GetSlots returns the value of Slots.
func (s *LayoutMember) GetSlots() int {
	return s.Slots
}

// SetID sets the value of ID.
func (s *LayoutMember) SetID(val string) {
	s.ID = val
}

// SetZone sets the value of Zone.
func (s *LayoutMember) SetZone(val OptString) {
	s.Zone = val
}

// SetRack sets the value of Rack.
func (s *LayoutMember) SetRack(val OptString) {
	s.Rack = val
}

// SetCapacity sets the value of Capacity.
func (s *LayoutMember) SetCapacity(val uint64) {
	s.Capacity = val
}

// SetSlots sets the value of Slots.
func (s *LayoutMember) SetSlots(val int) {
	s.Slots = val
}

// Ref: #/components/schemas/LayoutRole
type LayoutRole struct {
	ID   string    `json:"id"`
	Zone OptString `json:"zone"`
	Rack OptString `json:"rack"`
	// Bytes of data the node takes. Zero makes it a gateway that holds no slots.
	Capacity uint64 `json:"capacity"`
}

// GetID returns the value of ID.
func (s *LayoutRole) GetID() string {
	return s.ID
}

// GetZone returns the value of Zone.
func (s *LayoutRole) GetZone() OptString {
	return s.Zone
}

// GetRack returns the value of Rack.
func (s *LayoutRole) GetRack() OptString {
	return s.Rack
}

// GetCapacity returns the value of Capacity.
func (s *LayoutRole) GetCapacity() uint64 {
	return s.Capacity
}

// SetID sets the value of ID.
func (s *LayoutRole) SetID(val string) {
	s.ID = val
}

// SetZone sets the value of Zone.
func (s *LayoutRole) SetZone(val OptString) {
	s.Zone = val
}

// SetRack sets the value of Rack.
func (s *LayoutRole) SetRack(val OptString) {
	s.Rack = val
}

// SetCapacity sets the value of Capacity.
func (s *LayoutRole) SetCapacity(val uint64) {
	s.Capacity = val
}

// Ref: #/components/schemas/LayoutSpread
type LayoutSpread struct {
	Width int `json:"width"`
	// Most slots of one partition's first width slots in a single zone.
	MaxPerZone int `json:"max_per_zone"`
	// Most slots of one partition's first width slots in a single rack.
	MaxPerRack int `json:"max_per_rack"`
}

// GetWidth returns the value of Width.
func (s *LayoutSpread) GetWidth() int {
	return s.Width
}

// GetMaxPerZone returns the value of MaxPerZone.
func (s *LayoutSpread) GetMaxPerZone() int {
	return s.MaxPerZone
}

// GetMaxPerRack returns the value of MaxPerRack.
func (s *LayoutSpread) GetMaxPerRack() int {
	return s.MaxPerRack
}

// SetWidth sets the value of Width.
func (s *LayoutSpread) SetWidth(val int) {
	s.Width = val
}

// SetMaxPerZone sets the value of MaxPerZone.
func (s *LayoutSpread) SetMaxPerZone(val int) {
	s.MaxPerZone = val
}

// SetMaxPerRack sets the value of MaxPerRack.
func (s *LayoutSpread) SetMaxPerRack(val int) {
	s.MaxPerRack = val
}

// NewOptBool returns new OptBool with value set to v.
func NewOptBool(v bool) OptBool {
	return OptBool{
		Value: v,
		Set:   true,
	}
}

// OptBool is optional bool.
type OptBool struct {
	Value bool
	Set   bool
}

// IsSet returns true if OptBool was set.
func (o OptBool) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptBool) Reset() {
	var v bool
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptBool) SetTo(v bool) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptBool) Get() (v bool, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptBool) Or(d bool) bool {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptDateTime returns new OptDateTime with value set to v.
func NewOptDateTime(v time.Time) OptDateTime {
	return OptDateTime{
		Value: v,
		Set:   true,
	}
}

// OptDateTime is optional time.Time.
type OptDateTime struct {
	Value time.Time
	Set   bool
}

// IsSet returns true if OptDateTime was set.
func (o OptDateTime) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptDateTime) Reset() {
	var v time.Time
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptDateTime) SetTo(v time.Time) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptDateTime) Get() (v time.Time, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptDateTime) Or(d time.Time) time.Time {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptInt returns new OptInt with value set to v.
func NewOptInt(v int) OptInt {
	return OptInt{
		Value: v,
		Set:   true,
	}
}

// OptInt is optional int.
type OptInt struct {
	Value int
	Set   bool
}

// IsSet returns true if OptInt was set.
func (o OptInt) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptInt) Reset() {
	var v int
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptInt) SetTo(v int) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptInt) Get() (v int, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptInt) Or(d int) int {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptString returns new OptString with value set to v.
func NewOptString(v string) OptString {
	return OptString{
		Value: v,
		Set:   true,
	}
}

// OptString is optional string.
type OptString struct {
	Value string
	Set   bool
}

// IsSet returns true if OptString was set.
func (o OptString) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptString) Reset() {
	var v string
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptString) SetTo(v string) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptString) Get() (v string, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptString) Or(d string) string {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptUint64 returns new OptUint64 with value set to v.
func NewOptUint64(v uint64) OptUint64 {
	return OptUint64{
		Value: v,
		Set:   true,
	}
}

// OptUint64 is optional uint64.
type OptUint64 struct {
	Value uint64
	Set   bool
}

// IsSet returns true if OptUint64 was set.
func (o OptUint64) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptUint64) Reset() {
	var v uint64
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptUint64) SetTo(v uint64) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptUint64) Get() (v uint64, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptUint64) Or(d uint64) uint64 {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// Access level; Admin includes Write includes Read.
// Ref: #/components/schemas/Permission
type Permission string

const (
	PermissionRead  Permission = "read"
	PermissionWrite Permission = "write"
	PermissionAdmin Permission = "admin"
)

// AllValues returns all Permission values.
func (Permission) AllValues() []Permission {
	return []Permission{
		PermissionRead,
		PermissionWrite,
		PermissionAdmin,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s Permission) MarshalText() ([]byte, error) {
	switch s {
	case PermissionRead:
		return []byte(s), nil
	case PermissionWrite:
		return []byte(s), nil
	case PermissionAdmin:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *Permission) UnmarshalText(data []byte) error {
	switch Permission(data) {
	case PermissionRead:
		*s = PermissionRead
		return nil
	case PermissionWrite:
		*s = PermissionWrite
		return nil
	case PermissionAdmin:
		*s = PermissionAdmin
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// Ref: #/components/schemas/ReloadResult
type ReloadResult struct {
	// What the reload applied: any of "credentials", "tls".
	Reloaded []string `json:"reloaded"`
	// The config revision in effect after the reload (see InstanceInfo.config_revision).
	ConfigRevision OptString `json:"config_revision"`
}

// GetReloaded returns the value of Reloaded.
func (s *ReloadResult) GetReloaded() []string {
	return s.Reloaded
}

// GetConfigRevision returns the value of ConfigRevision.
func (s *ReloadResult) GetConfigRevision() OptString {
	return s.ConfigRevision
}

// SetReloaded sets the value of Reloaded.
func (s *ReloadResult) SetReloaded(val []string) {
	s.Reloaded = val
}

// SetConfigRevision sets the value of ConfigRevision.
func (s *ReloadResult) SetConfigRevision(val OptString) {
	s.ConfigRevision = val
}

// Ref: #/components/schemas/RotateResult
type RotateResult struct {
	// Data keys moved onto the current master key by this run.
	Rewrapped int `json:"rewrapped"`
	// Data keys already under the current master key.
	Current int `json:"current"`
	// Data keys that could not be moved; the old master key must stay while this is not 0.
	Remaining int `json:"remaining"`
	// Up to 100 of the versions not moved, as bucket/key@version: reason.
	Failed []string `json:"failed"`
}

// GetRewrapped returns the value of Rewrapped.
func (s *RotateResult) GetRewrapped() int {
	return s.Rewrapped
}

// GetCurrent returns the value of Current.
func (s *RotateResult) GetCurrent() int {
	return s.Current
}

// GetRemaining returns the value of Remaining.
func (s *RotateResult) GetRemaining() int {
	return s.Remaining
}

// GetFailed returns the value of Failed.
func (s *RotateResult) GetFailed() []string {
	return s.Failed
}

// SetRewrapped sets the value of Rewrapped.
func (s *RotateResult) SetRewrapped(val int) {
	s.Rewrapped = val
}

// SetCurrent sets the value of Current.
func (s *RotateResult) SetCurrent(val int) {
	s.Current = val
}

// SetRemaining sets the value of Remaining.
func (s *RotateResult) SetRemaining(val int) {
	s.Remaining = val
}

// SetFailed sets the value of Failed.
func (s *RotateResult) SetFailed(val []string) {
	s.Failed = val
}

// Where the credential is defined.
// Ref: #/components/schemas/Source
type Source string

const (
	SourceConfig  Source = "config"
	SourceManaged Source = "managed"
)

// AllValues returns all Source values.
func (Source) AllValues() []Source {
	return []Source{
		SourceConfig,
		SourceManaged,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s Source) MarshalText() ([]byte, error) {
	switch s {
	case SourceConfig:
		return []byte(s), nil
	case SourceManaged:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *Source) UnmarshalText(data []byte) error {
	switch Source(data) {
	case SourceConfig:
		*s = SourceConfig
		return nil
	case SourceManaged:
		*s = SourceManaged
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}
