// Code generated by ogen, DO NOT EDIT.

package adminapi

import (
	"context"
	"io"
	"net/url"
	"strings"
	"time"

	"github.com/go-faster/errors"
	"github.com/ogen-go/ogen/conv"
	ht "github.com/ogen-go/ogen/http"
	"github.com/ogen-go/ogen/otelogen"
	"github.com/ogen-go/ogen/uri"
	"go.opentelemetry.io/otel/attribute"
	"go.opentelemetry.io/otel/codes"
	"go.opentelemetry.io/otel/metric"
	semconv "go.opentelemetry.io/otel/semconv/v1.39.0"
	"go.opentelemetry.io/otel/trace"
)

func trimTrailingSlashes(u *url.URL) {
	u.Path = strings.TrimRight(u.Path, "/")
	u.RawPath = strings.TrimRight(u.RawPath, "/")
}

// Invoker invokes operations described by OpenAPI v3 specification.
type Invoker interface {
	// ApplyMigrations invokes applyMigrations operation.
	//
	// Apply every pending migration in order, under the cluster-wide migrate election, and record the new
	// schema version — the admin-API equivalent of `fs cluster migrate`. Run it once a rolling upgrade
	// has replaced every node's binary; until then the cluster keeps operating at the old schema. Returns
	// 409 when a migration is already running or when the cluster's schema is newer than this binary
	// implements.
	//
	// POST /api/v1/cluster/migrate
	ApplyMigrations(ctx context.Context) (*MigrationStatus, error)
	// ClearDiskWeight invokes clearDiskWeight operation.
	//
	// Restore the weight the node registers from its config. Clearing an override that is not set is not
	// an error. Returns 501 when the server is not in cluster mode.
	//
	// DELETE /api/v1/cluster/disk-weights/{node}/{disk}
	ClearDiskWeight(ctx context.Context, params ClearDiskWeightParams) error
	// ControlRebalance invokes controlRebalance operation.
	//
	// Start, pause or resume the cluster-wide rebalance from this node. At most one rebalance runs
	// cluster-wide (etcd election); starting on several nodes leaves the extras waiting as standby
	// runners. Pausing stops this node's runner and keeps the resume cursor, so a later start/resume —
	// on any node — continues where it left off.
	//
	// POST /api/v1/cluster/rebalance
	ControlRebalance(ctx context.Context, request *RebalanceControlRequest) (*RebalanceStatus, error)
	// CreateAccessKey invokes createAccessKey operation.
	//
	// Create a runtime credential. The access key and secret are generated when not supplied. The secret
	// is returned only in this response and cannot be retrieved later.
	//
	// POST /api/v1/access-keys
	CreateAccessKey(ctx context.Context, request *CreateAccessKeyRequest) (*CreatedAccessKey, error)
	// DeleteAccessKey invokes deleteAccessKey operation.
	//
	// Remove a runtime credential. Config-defined credentials cannot be deleted.
	//
	// DELETE /api/v1/access-keys/{accessKey}
	DeleteAccessKey(ctx context.Context, params DeleteAccessKeyParams) error
	// GetBucketScheme invokes getBucketScheme operation.
	//
	// The bucket's effective replication scheme, its explicit override (empty when the bucket follows the
	// cluster default) and the cluster default. Returns 404 when the bucket does not exist and 501 when
	// the server is not in cluster mode (a single-node server has no per-bucket schemes).
	//
	// GET /api/v1/buckets/{bucket}/scheme
	GetBucketScheme(ctx context.Context, params GetBucketSchemeParams) (*BucketScheme, error)
	// GetBucketUsage invokes getBucketUsage operation.
	//
	// How many objects each bucket holds and how many bytes they occupy, read from the cluster's durable
	// usage index rather than computed on demand — counting on demand would mean a scatter-gather over
	// every disk, which is exactly what makes it unusable at the size where the question matters. The
	// totals are maintained incrementally as objects are written and deleted, and re-derived from the
	// objects themselves by a periodic cluster-wide recount. Between recounts a total can drift: a node
	// that dies between committing a write and reporting it leaves its bucket short. Read `counted` to see
	// when a total was last anchored, and `updated` for the last incremental change. Multipart uploads are
	// counted only once completed; parts in flight are not objects and are not charged to the bucket.
	// Returns 501 when the server is not in cluster mode.
	//
	// GET /api/v1/buckets/usage
	GetBucketUsage(ctx context.Context) (*BucketUsageList, error)
	// GetClusterStatus invokes getClusterStatus operation.
	//
	// Cluster-wide view read from the control plane: the agreed schema version, every node with its disks
	// and reported capacity, aggregate capacity, placement skew and whether a rebalance is currently
	// running. State is "disabled" when the server is not in cluster mode.
	//
	// GET /api/v1/cluster/status
	GetClusterStatus(ctx context.Context) (*ClusterStatus, error)
	// GetInfo invokes getInfo operation.
	//
	// Build information, uptime and whether authentication is enabled.
	//
	// GET /api/v1/info
	GetInfo(ctx context.Context) (*InstanceInfo, error)
	// GetMigrationStatus invokes getMigrationStatus operation.
	//
	// The schema version the cluster has agreed on, the version this binary implements, and the migrations
	// still pending between them. State is "disabled" when the server is not in cluster mode.
	//
	// GET /api/v1/cluster/migrate
	GetMigrationStatus(ctx context.Context) (*MigrationStatus, error)
	// GetPublicReadBuckets invokes getPublicReadBuckets operation.
	//
	// Buckets readable anonymously (unsigned GET/HEAD/list), cluster-wide. Available only with
	// cluster-wide credentials (auth.source: etcd); returns 501 otherwise, where public-read buckets are
	// managed in the config file per node.
	//
	// GET /api/v1/public-read-buckets
	GetPublicReadBuckets(ctx context.Context) (*PublicReadBuckets, error)
	// GetRebalanceStatus invokes getRebalanceStatus operation.
	//
	// State and progress of the cluster rebalance runner on this node, the persisted resume cursor and the
	// depth of the async repair queue. State is "disabled" when the server is not in cluster mode.
	//
	// GET /api/v1/cluster/rebalance
	GetRebalanceStatus(ctx context.Context) (*RebalanceStatus, error)
	// ListAccessKeys invokes listAccessKeys operation.
	//
	// Every credential the server accepts, secrets omitted.
	//
	// GET /api/v1/access-keys
	ListAccessKeys(ctx context.Context) (*AccessKeyList, error)
	// ListDiskWeights invokes listDiskWeights operation.
	//
	// Every per-disk placement weight override currently set. An override replaces the weight the node
	// registers from its config, and survives the node restarting — it is how a disk is drained without
	// editing a config file. Returns 501 when the server is not in cluster mode.
	//
	// GET /api/v1/cluster/disk-weights
	ListDiskWeights(ctx context.Context) (*DiskWeightList, error)
	// ReloadConfig invokes reloadConfig operation.
	//
	// Re-read the configuration file and apply the parts that change without a restart — the
	// config-defined credentials and grants, the anonymously readable buckets and the TLS certificate —
	// exactly as SIGHUP does. Runtime credentials created through this API are preserved. Returns what was
	// reloaded and the config revision now in effect, so an orchestrator can confirm a config change
	// landed without shelling into the process. Returns 501 on a listener with nothing to reload (the
	// headless cluster admin serves no S3 data).
	//
	// POST /api/v1/reload
	ReloadConfig(ctx context.Context) (*ReloadResult, error)
	// SetBucketScheme invokes setBucketScheme operation.
	//
	// Override the bucket's replication scheme, or clear the override to restore the cluster default. The
	// scheme must parse ("rf2.5", "rf3" or "ec:k,m") and the current topology must be able to host it. The
	// change affects new writes cluster-wide within seconds; existing objects convert through
	// repair/rebalance. Returns the effective scheme after applying. Returns 400 when the scheme is
	// invalid or the topology cannot host it, 404 when the bucket does not exist and 501 when the server
	// is not in cluster mode.
	//
	// PUT /api/v1/buckets/{bucket}/scheme
	SetBucketScheme(ctx context.Context, request *SetBucketSchemeRequest, params SetBucketSchemeParams) (*BucketScheme, error)
	// SetDiskWeight invokes setDiskWeight operation.
	//
	// Set the weight placement uses for one disk, until it is cleared. A weight that is not positive
	// drains the disk: no new data is placed on it and the auto-rebalancer moves what it holds elsewhere.
	// The override lives outside the node's registration, so a node republishing its record — which it
	// does on every capacity refresh and every restart — does not undo it. Accepted while the node is
	// down: the moment an operator most wants to drain a disk is often the moment it is unreachable. An
	// override for a disk that never appears is inert. Returns 501 when the server is not in cluster mode.
	//
	// PUT /api/v1/cluster/disk-weights/{node}/{disk}
	SetDiskWeight(ctx context.Context, request *SetDiskWeightRequest, params SetDiskWeightParams) (*DiskWeight, error)
	// SetPublicReadBuckets invokes setPublicReadBuckets operation.
	//
	// Replace the cluster-wide public-read bucket list. The change propagates to every node within seconds
	// with no restart. Returns the stored list. Returns 400 on an invalid bucket name and 501 when not
	// using cluster-wide credentials.
	//
	// PUT /api/v1/public-read-buckets
	SetPublicReadBuckets(ctx context.Context, request *SetPublicReadBucketsRequest) (*PublicReadBuckets, error)
}

// Client implements OAS client.
type Client struct {
	serverURL *url.URL
	baseClient
}

// NewClient initializes new Client defined by OAS.
func NewClient(serverURL string, opts ...ClientOption) (*Client, error) {
	u, err := url.Parse(serverURL)
	if err != nil {
		return nil, err
	}
	trimTrailingSlashes(u)

	c, err := newClientConfig(opts...).baseClient()
	if err != nil {
		return nil, err
	}
	return &Client{
		serverURL:  u,
		baseClient: c,
	}, nil
}

type serverURLKey struct{}

// WithServerURL sets context key to override server URL.
func WithServerURL(ctx context.Context, u *url.URL) context.Context {
	return context.WithValue(ctx, serverURLKey{}, u)
}

func (c *Client) requestURL(ctx context.Context) *url.URL {
	u, ok := ctx.Value(serverURLKey{}).(*url.URL)
	if !ok {
		return c.serverURL
	}
	return u
}

// ApplyMigrations invokes applyMigrations operation.
//
// Apply every pending migration in order, under the cluster-wide migrate election, and record the new
// schema version — the admin-API equivalent of `fs cluster migrate`. Run it once a rolling upgrade
// has replaced every node's binary; until then the cluster keeps operating at the old schema. Returns
// 409 when a migration is already running or when the cluster's schema is newer than this binary
// implements.
//
// POST /api/v1/cluster/migrate
func (c *Client) ApplyMigrations(ctx context.Context) (*MigrationStatus, error) {
	res, err := c.sendApplyMigrations(ctx)
	return res, err
}

func (c *Client) sendApplyMigrations(ctx context.Context) (res *MigrationStatus, err error) {
	otelAttrs := []attribute.KeyValue{
		otelogen.OperationID("applyMigrations"),
		semconv.HTTPRequestMethodKey.String("POST"),
		semconv.URLTemplateKey.String("/api/v1/cluster/migrate"),
	}
	otelAttrs = append(otelAttrs, c.cfg.Attributes...)

	// Run stopwatch.
	startTime := time.Now()
	defer func() {
		// Use floating point division here for higher precision (instead of Millisecond method).
		elapsedDuration := time.Since(startTime)
		c.duration.Record(ctx, float64(elapsedDuration)/float64(time.Millisecond), metric.WithAttributes(otelAttrs...))
	}()

	// Increment request counter.
	c.requests.Add(ctx, 1, metric.WithAttributes(otelAttrs...))

	// Start a span for this request.
	ctx, span := c.cfg.Tracer.Start(ctx, ApplyMigrationsOperation,
		trace.WithAttributes(otelAttrs...),
		clientSpanKind,
	)
	// Track stage for error reporting.
	var stage string
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, stage)
			c.errors.Add(ctx, 1, metric.WithAttributes(otelAttrs...))
		}
		span.End()
	}()

	stage = "BuildURL"
	u := uri.Clone(c.requestURL(ctx))
	var pathParts [1]string
	pathParts[0] = "/api/v1/cluster/migrate"
	uri.AddPathParts(u, pathParts[:]...)

	stage = "EncodeRequest"
	r, err := ht.NewRequest(ctx, "POST", u)
	if err != nil {
		return res, errors.Wrap(err, "create request")
	}

	stage = "SendRequest"
	resp, err := c.cfg.Client.Do(r)
	if err != nil {
		return res, errors.Wrap(err, "do request")
	}
	body := resp.Body
	defer func() {
		// Drain the body to EOF before closing, so the underlying
		// connection can be reused by the Transport regardless of the
		// response status code. See https://github.com/ogen-go/ogen/issues/1670.
		_, _ = io.Copy(io.Discard, body)
		_ = body.Close()
	}()

	stage = "DecodeResponse"
	result, err := decodeApplyMigrationsResponse(resp)
	if err != nil {
		return res, errors.Wrap(err, "decode response")
	}

	return result, nil
}

// ClearDiskWeight invokes clearDiskWeight operation.
//
// Restore the weight the node registers from its config. Clearing an override that is not set is not
// an error. Returns 501 when the server is not in cluster mode.
//
// DELETE /api/v1/cluster/disk-weights/{node}/{disk}
func (c *Client) ClearDiskWeight(ctx context.Context, params ClearDiskWeightParams) error {
	_, err := c.sendClearDiskWeight(ctx, params)
	return err
}

func (c *Client) sendClearDiskWeight(ctx context.Context, params ClearDiskWeightParams) (res *ClearDiskWeightNoContent, err error) {
	otelAttrs := []attribute.KeyValue{
		otelogen.OperationID("clearDiskWeight"),
		semconv.HTTPRequestMethodKey.String("DELETE"),
		semconv.URLTemplateKey.String("/api/v1/cluster/disk-weights/{node}/{disk}"),
	}
	otelAttrs = append(otelAttrs, c.cfg.Attributes...)

	// Run stopwatch.
	startTime := time.Now()
	defer func() {
		// Use floating point division here for higher precision (instead of Millisecond method).
		elapsedDuration := time.Since(startTime)
		c.duration.Record(ctx, float64(elapsedDuration)/float64(time.Millisecond), metric.WithAttributes(otelAttrs...))
	}()

	// Increment request counter.
	c.requests.Add(ctx, 1, metric.WithAttributes(otelAttrs...))

	// Start a span for this request.
	ctx, span := c.cfg.Tracer.Start(ctx, ClearDiskWeightOperation,
		trace.WithAttributes(otelAttrs...),
		clientSpanKind,
	)
	// Track stage for error reporting.
	var stage string
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, stage)
			c.errors.Add(ctx, 1, metric.WithAttributes(otelAttrs...))
		}
		span.End()
	}()

	stage = "BuildURL"
	u := uri.Clone(c.requestURL(ctx))
	var pathParts [4]string
	pathParts[0] = "/api/v1/cluster/disk-weights/"
	{
		// Encode "node" parameter.
		e := uri.NewPathEncoder(uri.PathEncoderConfig{
			Param:   "node",
			Style:   uri.PathStyleSimple,
			Explode: false,
		})
		if err := func() error {
			return e.EncodeValue(conv.StringToString(params.Node))
		}(); err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		encoded, err := e.Result()
		if err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		pathParts[1] = encoded
	}
	pathParts[2] = "/"
	{
		// Encode "disk" parameter.
		e := uri.NewPathEncoder(uri.PathEncoderConfig{
			Param:   "disk",
			Style:   uri.PathStyleSimple,
			Explode: false,
		})
		if err := func() error {
			return e.EncodeValue(conv.StringToString(params.Disk))
		}(); err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		encoded, err := e.Result()
		if err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		pathParts[3] = encoded
	}
	uri.AddPathParts(u, pathParts[:]...)

	stage = "EncodeRequest"
	r, err := ht.NewRequest(ctx, "DELETE", u)
	if err != nil {
		return res, errors.Wrap(err, "create request")
	}

	stage = "SendRequest"
	resp, err := c.cfg.Client.Do(r)
	if err != nil {
		return res, errors.Wrap(err, "do request")
	}
	body := resp.Body
	defer func() {
		// Drain the body to EOF before closing, so the underlying
		// connection can be reused by the Transport regardless of the
		// response status code. See https://github.com/ogen-go/ogen/issues/1670.
		_, _ = io.Copy(io.Discard, body)
		_ = body.Close()
	}()

	stage = "DecodeResponse"
	result, err := decodeClearDiskWeightResponse(resp)
	if err != nil {
		return res, errors.Wrap(err, "decode response")
	}

	return result, nil
}

// ControlRebalance invokes controlRebalance operation.
//
// Start, pause or resume the cluster-wide rebalance from this node. At most one rebalance runs
// cluster-wide (etcd election); starting on several nodes leaves the extras waiting as standby
// runners. Pausing stops this node's runner and keeps the resume cursor, so a later start/resume —
// on any node — continues where it left off.
//
// POST /api/v1/cluster/rebalance
func (c *Client) ControlRebalance(ctx context.Context, request *RebalanceControlRequest) (*RebalanceStatus, error) {
	res, err := c.sendControlRebalance(ctx, request)
	return res, err
}

func (c *Client) sendControlRebalance(ctx context.Context, request *RebalanceControlRequest) (res *RebalanceStatus, err error) {
	otelAttrs := []attribute.KeyValue{
		otelogen.OperationID("controlRebalance"),
		semconv.HTTPRequestMethodKey.String("POST"),
		semconv.URLTemplateKey.String("/api/v1/cluster/rebalance"),
	}
	otelAttrs = append(otelAttrs, c.cfg.Attributes...)

	// Run stopwatch.
	startTime := time.Now()
	defer func() {
		// Use floating point division here for higher precision (instead of Millisecond method).
		elapsedDuration := time.Since(startTime)
		c.duration.Record(ctx, float64(elapsedDuration)/float64(time.Millisecond), metric.WithAttributes(otelAttrs...))
	}()

	// Increment request counter.
	c.requests.Add(ctx, 1, metric.WithAttributes(otelAttrs...))

	// Start a span for this request.
	ctx, span := c.cfg.Tracer.Start(ctx, ControlRebalanceOperation,
		trace.WithAttributes(otelAttrs...),
		clientSpanKind,
	)
	// Track stage for error reporting.
	var stage string
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, stage)
			c.errors.Add(ctx, 1, metric.WithAttributes(otelAttrs...))
		}
		span.End()
	}()

	stage = "BuildURL"
	u := uri.Clone(c.requestURL(ctx))
	var pathParts [1]string
	pathParts[0] = "/api/v1/cluster/rebalance"
	uri.AddPathParts(u, pathParts[:]...)

	stage = "EncodeRequest"
	r, err := ht.NewRequest(ctx, "POST", u)
	if err != nil {
		return res, errors.Wrap(err, "create request")
	}
	if err := encodeControlRebalanceRequest(request, r); err != nil {
		return res, errors.Wrap(err, "encode request")
	}

	stage = "SendRequest"
	resp, err := c.cfg.Client.Do(r)
	if err != nil {
		return res, errors.Wrap(err, "do request")
	}
	body := resp.Body
	defer func() {
		// Drain the body to EOF before closing, so the underlying
		// connection can be reused by the Transport regardless of the
		// response status code. See https://github.com/ogen-go/ogen/issues/1670.
		_, _ = io.Copy(io.Discard, body)
		_ = body.Close()
	}()

	stage = "DecodeResponse"
	result, err := decodeControlRebalanceResponse(resp)
	if err != nil {
		return res, errors.Wrap(err, "decode response")
	}

	return result, nil
}

// CreateAccessKey invokes createAccessKey operation.
//
// Create a runtime credential. The access key and secret are generated when not supplied. The secret
// is returned only in this response and cannot be retrieved later.
//
// POST /api/v1/access-keys
func (c *Client) CreateAccessKey(ctx context.Context, request *CreateAccessKeyRequest) (*CreatedAccessKey, error) {
	res, err := c.sendCreateAccessKey(ctx, request)
	return res, err
}

func (c *Client) sendCreateAccessKey(ctx context.Context, request *CreateAccessKeyRequest) (res *CreatedAccessKey, err error) {
	otelAttrs := []attribute.KeyValue{
		otelogen.OperationID("createAccessKey"),
		semconv.HTTPRequestMethodKey.String("POST"),
		semconv.URLTemplateKey.String("/api/v1/access-keys"),
	}
	otelAttrs = append(otelAttrs, c.cfg.Attributes...)

	// Run stopwatch.
	startTime := time.Now()
	defer func() {
		// Use floating point division here for higher precision (instead of Millisecond method).
		elapsedDuration := time.Since(startTime)
		c.duration.Record(ctx, float64(elapsedDuration)/float64(time.Millisecond), metric.WithAttributes(otelAttrs...))
	}()

	// Increment request counter.
	c.requests.Add(ctx, 1, metric.WithAttributes(otelAttrs...))

	// Start a span for this request.
	ctx, span := c.cfg.Tracer.Start(ctx, CreateAccessKeyOperation,
		trace.WithAttributes(otelAttrs...),
		clientSpanKind,
	)
	// Track stage for error reporting.
	var stage string
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, stage)
			c.errors.Add(ctx, 1, metric.WithAttributes(otelAttrs...))
		}
		span.End()
	}()

	stage = "BuildURL"
	u := uri.Clone(c.requestURL(ctx))
	var pathParts [1]string
	pathParts[0] = "/api/v1/access-keys"
	uri.AddPathParts(u, pathParts[:]...)

	stage = "EncodeRequest"
	r, err := ht.NewRequest(ctx, "POST", u)
	if err != nil {
		return res, errors.Wrap(err, "create request")
	}
	if err := encodeCreateAccessKeyRequest(request, r); err != nil {
		return res, errors.Wrap(err, "encode request")
	}

	stage = "SendRequest"
	resp, err := c.cfg.Client.Do(r)
	if err != nil {
		return res, errors.Wrap(err, "do request")
	}
	body := resp.Body
	defer func() {
		// Drain the body to EOF before closing, so the underlying
		// connection can be reused by the Transport regardless of the
		// response status code. See https://github.com/ogen-go/ogen/issues/1670.
		_, _ = io.Copy(io.Discard, body)
		_ = body.Close()
	}()

	stage = "DecodeResponse"
	result, err := decodeCreateAccessKeyResponse(resp)
	if err != nil {
		return res, errors.Wrap(err, "decode response")
	}

	return result, nil
}

// DeleteAccessKey invokes deleteAccessKey operation.
//
// Remove a runtime credential. Config-defined credentials cannot be deleted.
//
// DELETE /api/v1/access-keys/{accessKey}
func (c *Client) DeleteAccessKey(ctx context.Context, params DeleteAccessKeyParams) error {
	_, err := c.sendDeleteAccessKey(ctx, params)
	return err
}

func (c *Client) sendDeleteAccessKey(ctx context.Context, params DeleteAccessKeyParams) (res *DeleteAccessKeyNoContent, err error) {
	otelAttrs := []attribute.KeyValue{
		otelogen.OperationID("deleteAccessKey"),
		semconv.HTTPRequestMethodKey.String("DELETE"),
		semconv.URLTemplateKey.String("/api/v1/access-keys/{accessKey}"),
	}
	otelAttrs = append(otelAttrs, c.cfg.Attributes...)

	// Run stopwatch.
	startTime := time.Now()
	defer func() {
		// Use floating point division here for higher precision (instead of Millisecond method).
		elapsedDuration := time.Since(startTime)
		c.duration.Record(ctx, float64(elapsedDuration)/float64(time.Millisecond), metric.WithAttributes(otelAttrs...))
	}()

	// Increment request counter.
	c.requests.Add(ctx, 1, metric.WithAttributes(otelAttrs...))

	// Start a span for this request.
	ctx, span := c.cfg.Tracer.Start(ctx, DeleteAccessKeyOperation,
		trace.WithAttributes(otelAttrs...),
		clientSpanKind,
	)
	// Track stage for error reporting.
	var stage string
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, stage)
			c.errors.Add(ctx, 1, metric.WithAttributes(otelAttrs...))
		}
		span.End()
	}()

	stage = "BuildURL"
	u := uri.Clone(c.requestURL(ctx))
	var pathParts [2]string
	pathParts[0] = "/api/v1/access-keys/"
	{
		// Encode "accessKey" parameter.
		e := uri.NewPathEncoder(uri.PathEncoderConfig{
			Param:   "accessKey",
			Style:   uri.PathStyleSimple,
			Explode: false,
		})
		if err := func() error {
			return e.EncodeValue(conv.StringToString(params.AccessKey))
		}(); err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		encoded, err := e.Result()
		if err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		pathParts[1] = encoded
	}
	uri.AddPathParts(u, pathParts[:]...)

	stage = "EncodeRequest"
	r, err := ht.NewRequest(ctx, "DELETE", u)
	if err != nil {
		return res, errors.Wrap(err, "create request")
	}

	stage = "SendRequest"
	resp, err := c.cfg.Client.Do(r)
	if err != nil {
		return res, errors.Wrap(err, "do request")
	}
	body := resp.Body
	defer func() {
		// Drain the body to EOF before closing, so the underlying
		// connection can be reused by the Transport regardless of the
		// response status code. See https://github.com/ogen-go/ogen/issues/1670.
		_, _ = io.Copy(io.Discard, body)
		_ = body.Close()
	}()

	stage = "DecodeResponse"
	result, err := decodeDeleteAccessKeyResponse(resp)
	if err != nil {
		return res, errors.Wrap(err, "decode response")
	}

	return result, nil
}

// GetBucketScheme invokes getBucketScheme operation.
//
// The bucket's effective replication scheme, its explicit override (empty when the bucket follows the
// cluster default) and the cluster default. Returns 404 when the bucket does not exist and 501 when
// the server is not in cluster mode (a single-node server has no per-bucket schemes).
//
// GET /api/v1/buckets/{bucket}/scheme
func (c *Client) GetBucketScheme(ctx context.Context, params GetBucketSchemeParams) (*BucketScheme, error) {
	res, err := c.sendGetBucketScheme(ctx, params)
	return res, err
}

func (c *Client) sendGetBucketScheme(ctx context.Context, params GetBucketSchemeParams) (res *BucketScheme, err error) {
	otelAttrs := []attribute.KeyValue{
		otelogen.OperationID("getBucketScheme"),
		semconv.HTTPRequestMethodKey.String("GET"),
		semconv.URLTemplateKey.String("/api/v1/buckets/{bucket}/scheme"),
	}
	otelAttrs = append(otelAttrs, c.cfg.Attributes...)

	// Run stopwatch.
	startTime := time.Now()
	defer func() {
		// Use floating point division here for higher precision (instead of Millisecond method).
		elapsedDuration := time.Since(startTime)
		c.duration.Record(ctx, float64(elapsedDuration)/float64(time.Millisecond), metric.WithAttributes(otelAttrs...))
	}()

	// Increment request counter.
	c.requests.Add(ctx, 1, metric.WithAttributes(otelAttrs...))

	// Start a span for this request.
	ctx, span := c.cfg.Tracer.Start(ctx, GetBucketSchemeOperation,
		trace.WithAttributes(otelAttrs...),
		clientSpanKind,
	)
	// Track stage for error reporting.
	var stage string
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, stage)
			c.errors.Add(ctx, 1, metric.WithAttributes(otelAttrs...))
		}
		span.End()
	}()

	stage = "BuildURL"
	u := uri.Clone(c.requestURL(ctx))
	var pathParts [3]string
	pathParts[0] = "/api/v1/buckets/"
	{
		// Encode "bucket" parameter.
		e := uri.NewPathEncoder(uri.PathEncoderConfig{
			Param:   "bucket",
			Style:   uri.PathStyleSimple,
			Explode: false,
		})
		if err := func() error {
			return e.EncodeValue(conv.StringToString(params.Bucket))
		}(); err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		encoded, err := e.Result()
		if err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		pathParts[1] = encoded
	}
	pathParts[2] = "/scheme"
	uri.AddPathParts(u, pathParts[:]...)

	stage = "EncodeRequest"
	r, err := ht.NewRequest(ctx, "GET", u)
	if err != nil {
		return res, errors.Wrap(err, "create request")
	}

	stage = "SendRequest"
	resp, err := c.cfg.Client.Do(r)
	if err != nil {
		return res, errors.Wrap(err, "do request")
	}
	body := resp.Body
	defer func() {
		// Drain the body to EOF before closing, so the underlying
		// connection can be reused by the Transport regardless of the
		// response status code. See https://github.com/ogen-go/ogen/issues/1670.
		_, _ = io.Copy(io.Discard, body)
		_ = body.Close()
	}()

	stage = "DecodeResponse"
	result, err := decodeGetBucketSchemeResponse(resp)
	if err != nil {
		return res, errors.Wrap(err, "decode response")
	}

	return result, nil
}

// GetBucketUsage invokes getBucketUsage operation.
//
// How many objects each bucket holds and how many bytes they occupy, read from the cluster's durable
// usage index rather than computed on demand — counting on demand would mean a scatter-gather over
// every disk, which is exactly what makes it unusable at the size where the question matters. The
// totals are maintained incrementally as objects are written and deleted, and re-derived from the
// objects themselves by a periodic cluster-wide recount. Between recounts a total can drift: a node
// that dies between committing a write and reporting it leaves its bucket short. Read `counted` to see
// when a total was last anchored, and `updated` for the last incremental change. Multipart uploads are
// counted only once completed; parts in flight are not objects and are not charged to the bucket.
// Returns 501 when the server is not in cluster mode.
//
// GET /api/v1/buckets/usage
func (c *Client) GetBucketUsage(ctx context.Context) (*BucketUsageList, error) {
	res, err := c.sendGetBucketUsage(ctx)
	return res, err
}

func (c *Client) sendGetBucketUsage(ctx context.Context) (res *BucketUsageList, err error) {
	otelAttrs := []attribute.KeyValue{
		otelogen.OperationID("getBucketUsage"),
		semconv.HTTPRequestMethodKey.String("GET"),
		semconv.URLTemplateKey.String("/api/v1/buckets/usage"),
	}
	otelAttrs = append(otelAttrs, c.cfg.Attributes...)

	// Run stopwatch.
	startTime := time.Now()
	defer func() {
		// Use floating point division here for higher precision (instead of Millisecond method).
		elapsedDuration := time.Since(startTime)
		c.duration.Record(ctx, float64(elapsedDuration)/float64(time.Millisecond), metric.WithAttributes(otelAttrs...))
	}()

	// Increment request counter.
	c.requests.Add(ctx, 1, metric.WithAttributes(otelAttrs...))

	// Start a span for this request.
	ctx, span := c.cfg.Tracer.Start(ctx, GetBucketUsageOperation,
		trace.WithAttributes(otelAttrs...),
		clientSpanKind,
	)
	// Track stage for error reporting.
	var stage string
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, stage)
			c.errors.Add(ctx, 1, metric.WithAttributes(otelAttrs...))
		}
		span.End()
	}()

	stage = "BuildURL"
	u := uri.Clone(c.requestURL(ctx))
	var pathParts [1]string
	pathParts[0] = "/api/v1/buckets/usage"
	uri.AddPathParts(u, pathParts[:]...)

	stage = "EncodeRequest"
	r, err := ht.NewRequest(ctx, "GET", u)
	if err != nil {
		return res, errors.Wrap(err, "create request")
	}

	stage = "SendRequest"
	resp, err := c.cfg.Client.Do(r)
	if err != nil {
		return res, errors.Wrap(err, "do request")
	}
	body := resp.Body
	defer func() {
		// Drain the body to EOF before closing, so the underlying
		// connection can be reused by the Transport regardless of the
		// response status code. See https://github.com/ogen-go/ogen/issues/1670.
		_, _ = io.Copy(io.Discard, body)
		_ = body.Close()
	}()

	stage = "DecodeResponse"
	result, err := decodeGetBucketUsageResponse(resp)
	if err != nil {
		return res, errors.Wrap(err, "decode response")
	}

	return result, nil
}

// GetClusterStatus invokes getClusterStatus operation.
//
// Cluster-wide view read from the control plane: the agreed schema version, every node with its disks
// and reported capacity, aggregate capacity, placement skew and whether a rebalance is currently
// running. State is "disabled" when the server is not in cluster mode.
//
// GET /api/v1/cluster/status
func (c *Client) GetClusterStatus(ctx context.Context) (*ClusterStatus, error) {
	res, err := c.sendGetClusterStatus(ctx)
	return res, err
}

func (c *Client) sendGetClusterStatus(ctx context.Context) (res *ClusterStatus, err error) {
	otelAttrs := []attribute.KeyValue{
		otelogen.OperationID("getClusterStatus"),
		semconv.HTTPRequestMethodKey.String("GET"),
		semconv.URLTemplateKey.String("/api/v1/cluster/status"),
	}
	otelAttrs = append(otelAttrs, c.cfg.Attributes...)

	// Run stopwatch.
	startTime := time.Now()
	defer func() {
		// Use floating point division here for higher precision (instead of Millisecond method).
		elapsedDuration := time.Since(startTime)
		c.duration.Record(ctx, float64(elapsedDuration)/float64(time.Millisecond), metric.WithAttributes(otelAttrs...))
	}()

	// Increment request counter.
	c.requests.Add(ctx, 1, metric.WithAttributes(otelAttrs...))

	// Start a span for this request.
	ctx, span := c.cfg.Tracer.Start(ctx, GetClusterStatusOperation,
		trace.WithAttributes(otelAttrs...),
		clientSpanKind,
	)
	// Track stage for error reporting.
	var stage string
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, stage)
			c.errors.Add(ctx, 1, metric.WithAttributes(otelAttrs...))
		}
		span.End()
	}()

	stage = "BuildURL"
	u := uri.Clone(c.requestURL(ctx))
	var pathParts [1]string
	pathParts[0] = "/api/v1/cluster/status"
	uri.AddPathParts(u, pathParts[:]...)

	stage = "EncodeRequest"
	r, err := ht.NewRequest(ctx, "GET", u)
	if err != nil {
		return res, errors.Wrap(err, "create request")
	}

	stage = "SendRequest"
	resp, err := c.cfg.Client.Do(r)
	if err != nil {
		return res, errors.Wrap(err, "do request")
	}
	body := resp.Body
	defer func() {
		// Drain the body to EOF before closing, so the underlying
		// connection can be reused by the Transport regardless of the
		// response status code. See https://github.com/ogen-go/ogen/issues/1670.
		_, _ = io.Copy(io.Discard, body)
		_ = body.Close()
	}()

	stage = "DecodeResponse"
	result, err := decodeGetClusterStatusResponse(resp)
	if err != nil {
		return res, errors.Wrap(err, "decode response")
	}

	return result, nil
}

// GetInfo invokes getInfo operation.
//
// Build information, uptime and whether authentication is enabled.
//
// GET /api/v1/info
func (c *Client) GetInfo(ctx context.Context) (*InstanceInfo, error) {
	res, err := c.sendGetInfo(ctx)
	return res, err
}

func (c *Client) sendGetInfo(ctx context.Context) (res *InstanceInfo, err error) {
	otelAttrs := []attribute.KeyValue{
		otelogen.OperationID("getInfo"),
		semconv.HTTPRequestMethodKey.String("GET"),
		semconv.URLTemplateKey.String("/api/v1/info"),
	}
	otelAttrs = append(otelAttrs, c.cfg.Attributes...)

	// Run stopwatch.
	startTime := time.Now()
	defer func() {
		// Use floating point division here for higher precision (instead of Millisecond method).
		elapsedDuration := time.Since(startTime)
		c.duration.Record(ctx, float64(elapsedDuration)/float64(time.Millisecond), metric.WithAttributes(otelAttrs...))
	}()

	// Increment request counter.
	c.requests.Add(ctx, 1, metric.WithAttributes(otelAttrs...))

	// Start a span for this request.
	ctx, span := c.cfg.Tracer.Start(ctx, GetInfoOperation,
		trace.WithAttributes(otelAttrs...),
		clientSpanKind,
	)
	// Track stage for error reporting.
	var stage string
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, stage)
			c.errors.Add(ctx, 1, metric.WithAttributes(otelAttrs...))
		}
		span.End()
	}()

	stage = "BuildURL"
	u := uri.Clone(c.requestURL(ctx))
	var pathParts [1]string
	pathParts[0] = "/api/v1/info"
	uri.AddPathParts(u, pathParts[:]...)

	stage = "EncodeRequest"
	r, err := ht.NewRequest(ctx, "GET", u)
	if err != nil {
		return res, errors.Wrap(err, "create request")
	}

	stage = "SendRequest"
	resp, err := c.cfg.Client.Do(r)
	if err != nil {
		return res, errors.Wrap(err, "do request")
	}
	body := resp.Body
	defer func() {
		// Drain the body to EOF before closing, so the underlying
		// connection can be reused by the Transport regardless of the
		// response status code. See https://github.com/ogen-go/ogen/issues/1670.
		_, _ = io.Copy(io.Discard, body)
		_ = body.Close()
	}()

	stage = "DecodeResponse"
	result, err := decodeGetInfoResponse(resp)
	if err != nil {
		return res, errors.Wrap(err, "decode response")
	}

	return result, nil
}

// GetMigrationStatus invokes getMigrationStatus operation.
//
// The schema version the cluster has agreed on, the version this binary implements, and the migrations
// still pending between them. State is "disabled" when the server is not in cluster mode.
//
// GET /api/v1/cluster/migrate
func (c *Client) GetMigrationStatus(ctx context.Context) (*MigrationStatus, error) {
	res, err := c.sendGetMigrationStatus(ctx)
	return res, err
}

func (c *Client) sendGetMigrationStatus(ctx context.Context) (res *MigrationStatus, err error) {
	otelAttrs := []attribute.KeyValue{
		otelogen.OperationID("getMigrationStatus"),
		semconv.HTTPRequestMethodKey.String("GET"),
		semconv.URLTemplateKey.String("/api/v1/cluster/migrate"),
	}
	otelAttrs = append(otelAttrs, c.cfg.Attributes...)

	// Run stopwatch.
	startTime := time.Now()
	defer func() {
		// Use floating point division here for higher precision (instead of Millisecond method).
		elapsedDuration := time.Since(startTime)
		c.duration.Record(ctx, float64(elapsedDuration)/float64(time.Millisecond), metric.WithAttributes(otelAttrs...))
	}()

	// Increment request counter.
	c.requests.Add(ctx, 1, metric.WithAttributes(otelAttrs...))

	// Start a span for this request.
	ctx, span := c.cfg.Tracer.Start(ctx, GetMigrationStatusOperation,
		trace.WithAttributes(otelAttrs...),
		clientSpanKind,
	)
	// Track stage for error reporting.
	var stage string
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, stage)
			c.errors.Add(ctx, 1, metric.WithAttributes(otelAttrs...))
		}
		span.End()
	}()

	stage = "BuildURL"
	u := uri.Clone(c.requestURL(ctx))
	var pathParts [1]string
	pathParts[0] = "/api/v1/cluster/migrate"
	uri.AddPathParts(u, pathParts[:]...)

	stage = "EncodeRequest"
	r, err := ht.NewRequest(ctx, "GET", u)
	if err != nil {
		return res, errors.Wrap(err, "create request")
	}

	stage = "SendRequest"
	resp, err := c.cfg.Client.Do(r)
	if err != nil {
		return res, errors.Wrap(err, "do request")
	}
	body := resp.Body
	defer func() {
		// Drain the body to EOF before closing, so the underlying
		// connection can be reused by the Transport regardless of the
		// response status code. See https://github.com/ogen-go/ogen/issues/1670.
		_, _ = io.Copy(io.Discard, body)
		_ = body.Close()
	}()

	stage = "DecodeResponse"
	result, err := decodeGetMigrationStatusResponse(resp)
	if err != nil {
		return res, errors.Wrap(err, "decode response")
	}

	return result, nil
}

// GetPublicReadBuckets invokes getPublicReadBuckets operation.
//
// Buckets readable anonymously (unsigned GET/HEAD/list), cluster-wide. Available only with
// cluster-wide credentials (auth.source: etcd); returns 501 otherwise, where public-read buckets are
// managed in the config file per node.
//
// GET /api/v1/public-read-buckets
func (c *Client) GetPublicReadBuckets(ctx context.Context) (*PublicReadBuckets, error) {
	res, err := c.sendGetPublicReadBuckets(ctx)
	return res, err
}

func (c *Client) sendGetPublicReadBuckets(ctx context.Context) (res *PublicReadBuckets, err error) {
	otelAttrs := []attribute.KeyValue{
		otelogen.OperationID("getPublicReadBuckets"),
		semconv.HTTPRequestMethodKey.String("GET"),
		semconv.URLTemplateKey.String("/api/v1/public-read-buckets"),
	}
	otelAttrs = append(otelAttrs, c.cfg.Attributes...)

	// Run stopwatch.
	startTime := time.Now()
	defer func() {
		// Use floating point division here for higher precision (instead of Millisecond method).
		elapsedDuration := time.Since(startTime)
		c.duration.Record(ctx, float64(elapsedDuration)/float64(time.Millisecond), metric.WithAttributes(otelAttrs...))
	}()

	// Increment request counter.
	c.requests.Add(ctx, 1, metric.WithAttributes(otelAttrs...))

	// Start a span for this request.
	ctx, span := c.cfg.Tracer.Start(ctx, GetPublicReadBucketsOperation,
		trace.WithAttributes(otelAttrs...),
		clientSpanKind,
	)
	// Track stage for error reporting.
	var stage string
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, stage)
			c.errors.Add(ctx, 1, metric.WithAttributes(otelAttrs...))
		}
		span.End()
	}()

	stage = "BuildURL"
	u := uri.Clone(c.requestURL(ctx))
	var pathParts [1]string
	pathParts[0] = "/api/v1/public-read-buckets"
	uri.AddPathParts(u, pathParts[:]...)

	stage = "EncodeRequest"
	r, err := ht.NewRequest(ctx, "GET", u)
	if err != nil {
		return res, errors.Wrap(err, "create request")
	}

	stage = "SendRequest"
	resp, err := c.cfg.Client.Do(r)
	if err != nil {
		return res, errors.Wrap(err, "do request")
	}
	body := resp.Body
	defer func() {
		// Drain the body to EOF before closing, so the underlying
		// connection can be reused by the Transport regardless of the
		// response status code. See https://github.com/ogen-go/ogen/issues/1670.
		_, _ = io.Copy(io.Discard, body)
		_ = body.Close()
	}()

	stage = "DecodeResponse"
	result, err := decodeGetPublicReadBucketsResponse(resp)
	if err != nil {
		return res, errors.Wrap(err, "decode response")
	}

	return result, nil
}

// GetRebalanceStatus invokes getRebalanceStatus operation.
//
// State and progress of the cluster rebalance runner on this node, the persisted resume cursor and the
// depth of the async repair queue. State is "disabled" when the server is not in cluster mode.
//
// GET /api/v1/cluster/rebalance
func (c *Client) GetRebalanceStatus(ctx context.Context) (*RebalanceStatus, error) {
	res, err := c.sendGetRebalanceStatus(ctx)
	return res, err
}

func (c *Client) sendGetRebalanceStatus(ctx context.Context) (res *RebalanceStatus, err error) {
	otelAttrs := []attribute.KeyValue{
		otelogen.OperationID("getRebalanceStatus"),
		semconv.HTTPRequestMethodKey.String("GET"),
		semconv.URLTemplateKey.String("/api/v1/cluster/rebalance"),
	}
	otelAttrs = append(otelAttrs, c.cfg.Attributes...)

	// Run stopwatch.
	startTime := time.Now()
	defer func() {
		// Use floating point division here for higher precision (instead of Millisecond method).
		elapsedDuration := time.Since(startTime)
		c.duration.Record(ctx, float64(elapsedDuration)/float64(time.Millisecond), metric.WithAttributes(otelAttrs...))
	}()

	// Increment request counter.
	c.requests.Add(ctx, 1, metric.WithAttributes(otelAttrs...))

	// Start a span for this request.
	ctx, span := c.cfg.Tracer.Start(ctx, GetRebalanceStatusOperation,
		trace.WithAttributes(otelAttrs...),
		clientSpanKind,
	)
	// Track stage for error reporting.
	var stage string
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, stage)
			c.errors.Add(ctx, 1, metric.WithAttributes(otelAttrs...))
		}
		span.End()
	}()

	stage = "BuildURL"
	u := uri.Clone(c.requestURL(ctx))
	var pathParts [1]string
	pathParts[0] = "/api/v1/cluster/rebalance"
	uri.AddPathParts(u, pathParts[:]...)

	stage = "EncodeRequest"
	r, err := ht.NewRequest(ctx, "GET", u)
	if err != nil {
		return res, errors.Wrap(err, "create request")
	}

	stage = "SendRequest"
	resp, err := c.cfg.Client.Do(r)
	if err != nil {
		return res, errors.Wrap(err, "do request")
	}
	body := resp.Body
	defer func() {
		// Drain the body to EOF before closing, so the underlying
		// connection can be reused by the Transport regardless of the
		// response status code. See https://github.com/ogen-go/ogen/issues/1670.
		_, _ = io.Copy(io.Discard, body)
		_ = body.Close()
	}()

	stage = "DecodeResponse"
	result, err := decodeGetRebalanceStatusResponse(resp)
	if err != nil {
		return res, errors.Wrap(err, "decode response")
	}

	return result, nil
}

// ListAccessKeys invokes listAccessKeys operation.
//
// Every credential the server accepts, secrets omitted.
//
// GET /api/v1/access-keys
func (c *Client) ListAccessKeys(ctx context.Context) (*AccessKeyList, error) {
	res, err := c.sendListAccessKeys(ctx)
	return res, err
}

func (c *Client) sendListAccessKeys(ctx context.Context) (res *AccessKeyList, err error) {
	otelAttrs := []attribute.KeyValue{
		otelogen.OperationID("listAccessKeys"),
		semconv.HTTPRequestMethodKey.String("GET"),
		semconv.URLTemplateKey.String("/api/v1/access-keys"),
	}
	otelAttrs = append(otelAttrs, c.cfg.Attributes...)

	// Run stopwatch.
	startTime := time.Now()
	defer func() {
		// Use floating point division here for higher precision (instead of Millisecond method).
		elapsedDuration := time.Since(startTime)
		c.duration.Record(ctx, float64(elapsedDuration)/float64(time.Millisecond), metric.WithAttributes(otelAttrs...))
	}()

	// Increment request counter.
	c.requests.Add(ctx, 1, metric.WithAttributes(otelAttrs...))

	// Start a span for this request.
	ctx, span := c.cfg.Tracer.Start(ctx, ListAccessKeysOperation,
		trace.WithAttributes(otelAttrs...),
		clientSpanKind,
	)
	// Track stage for error reporting.
	var stage string
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, stage)
			c.errors.Add(ctx, 1, metric.WithAttributes(otelAttrs...))
		}
		span.End()
	}()

	stage = "BuildURL"
	u := uri.Clone(c.requestURL(ctx))
	var pathParts [1]string
	pathParts[0] = "/api/v1/access-keys"
	uri.AddPathParts(u, pathParts[:]...)

	stage = "EncodeRequest"
	r, err := ht.NewRequest(ctx, "GET", u)
	if err != nil {
		return res, errors.Wrap(err, "create request")
	}

	stage = "SendRequest"
	resp, err := c.cfg.Client.Do(r)
	if err != nil {
		return res, errors.Wrap(err, "do request")
	}
	body := resp.Body
	defer func() {
		// Drain the body to EOF before closing, so the underlying
		// connection can be reused by the Transport regardless of the
		// response status code. See https://github.com/ogen-go/ogen/issues/1670.
		_, _ = io.Copy(io.Discard, body)
		_ = body.Close()
	}()

	stage = "DecodeResponse"
	result, err := decodeListAccessKeysResponse(resp)
	if err != nil {
		return res, errors.Wrap(err, "decode response")
	}

	return result, nil
}

// ListDiskWeights invokes listDiskWeights operation.
//
// Every per-disk placement weight override currently set. An override replaces the weight the node
// registers from its config, and survives the node restarting — it is how a disk is drained without
// editing a config file. Returns 501 when the server is not in cluster mode.
//
// GET /api/v1/cluster/disk-weights
func (c *Client) ListDiskWeights(ctx context.Context) (*DiskWeightList, error) {
	res, err := c.sendListDiskWeights(ctx)
	return res, err
}

func (c *Client) sendListDiskWeights(ctx context.Context) (res *DiskWeightList, err error) {
	otelAttrs := []attribute.KeyValue{
		otelogen.OperationID("listDiskWeights"),
		semconv.HTTPRequestMethodKey.String("GET"),
		semconv.URLTemplateKey.String("/api/v1/cluster/disk-weights"),
	}
	otelAttrs = append(otelAttrs, c.cfg.Attributes...)

	// Run stopwatch.
	startTime := time.Now()
	defer func() {
		// Use floating point division here for higher precision (instead of Millisecond method).
		elapsedDuration := time.Since(startTime)
		c.duration.Record(ctx, float64(elapsedDuration)/float64(time.Millisecond), metric.WithAttributes(otelAttrs...))
	}()

	// Increment request counter.
	c.requests.Add(ctx, 1, metric.WithAttributes(otelAttrs...))

	// Start a span for this request.
	ctx, span := c.cfg.Tracer.Start(ctx, ListDiskWeightsOperation,
		trace.WithAttributes(otelAttrs...),
		clientSpanKind,
	)
	// Track stage for error reporting.
	var stage string
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, stage)
			c.errors.Add(ctx, 1, metric.WithAttributes(otelAttrs...))
		}
		span.End()
	}()

	stage = "BuildURL"
	u := uri.Clone(c.requestURL(ctx))
	var pathParts [1]string
	pathParts[0] = "/api/v1/cluster/disk-weights"
	uri.AddPathParts(u, pathParts[:]...)

	stage = "EncodeRequest"
	r, err := ht.NewRequest(ctx, "GET", u)
	if err != nil {
		return res, errors.Wrap(err, "create request")
	}

	stage = "SendRequest"
	resp, err := c.cfg.Client.Do(r)
	if err != nil {
		return res, errors.Wrap(err, "do request")
	}
	body := resp.Body
	defer func() {
		// Drain the body to EOF before closing, so the underlying
		// connection can be reused by the Transport regardless of the
		// response status code. See https://github.com/ogen-go/ogen/issues/1670.
		_, _ = io.Copy(io.Discard, body)
		_ = body.Close()
	}()

	stage = "DecodeResponse"
	result, err := decodeListDiskWeightsResponse(resp)
	if err != nil {
		return res, errors.Wrap(err, "decode response")
	}

	return result, nil
}

// ReloadConfig invokes reloadConfig operation.
//
// Re-read the configuration file and apply the parts that change without a restart — the
// config-defined credentials and grants, the anonymously readable buckets and the TLS certificate —
// exactly as SIGHUP does. Runtime credentials created through this API are preserved. Returns what was
// reloaded and the config revision now in effect, so an orchestrator can confirm a config change
// landed without shelling into the process. Returns 501 on a listener with nothing to reload (the
// headless cluster admin serves no S3 data).
//
// POST /api/v1/reload
func (c *Client) ReloadConfig(ctx context.Context) (*ReloadResult, error) {
	res, err := c.sendReloadConfig(ctx)
	return res, err
}

func (c *Client) sendReloadConfig(ctx context.Context) (res *ReloadResult, err error) {
	otelAttrs := []attribute.KeyValue{
		otelogen.OperationID("reloadConfig"),
		semconv.HTTPRequestMethodKey.String("POST"),
		semconv.URLTemplateKey.String("/api/v1/reload"),
	}
	otelAttrs = append(otelAttrs, c.cfg.Attributes...)

	// Run stopwatch.
	startTime := time.Now()
	defer func() {
		// Use floating point division here for higher precision (instead of Millisecond method).
		elapsedDuration := time.Since(startTime)
		c.duration.Record(ctx, float64(elapsedDuration)/float64(time.Millisecond), metric.WithAttributes(otelAttrs...))
	}()

	// Increment request counter.
	c.requests.Add(ctx, 1, metric.WithAttributes(otelAttrs...))

	// Start a span for this request.
	ctx, span := c.cfg.Tracer.Start(ctx, ReloadConfigOperation,
		trace.WithAttributes(otelAttrs...),
		clientSpanKind,
	)
	// Track stage for error reporting.
	var stage string
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, stage)
			c.errors.Add(ctx, 1, metric.WithAttributes(otelAttrs...))
		}
		span.End()
	}()

	stage = "BuildURL"
	u := uri.Clone(c.requestURL(ctx))
	var pathParts [1]string
	pathParts[0] = "/api/v1/reload"
	uri.AddPathParts(u, pathParts[:]...)

	stage = "EncodeRequest"
	r, err := ht.NewRequest(ctx, "POST", u)
	if err != nil {
		return res, errors.Wrap(err, "create request")
	}

	stage = "SendRequest"
	resp, err := c.cfg.Client.Do(r)
	if err != nil {
		return res, errors.Wrap(err, "do request")
	}
	body := resp.Body
	defer func() {
		// Drain the body to EOF before closing, so the underlying
		// connection can be reused by the Transport regardless of the
		// response status code. See https://github.com/ogen-go/ogen/issues/1670.
		_, _ = io.Copy(io.Discard, body)
		_ = body.Close()
	}()

	stage = "DecodeResponse"
	result, err := decodeReloadConfigResponse(resp)
	if err != nil {
		return res, errors.Wrap(err, "decode response")
	}

	return result, nil
}

// SetBucketScheme invokes setBucketScheme operation.
//
// Override the bucket's replication scheme, or clear the override to restore the cluster default. The
// scheme must parse ("rf2.5", "rf3" or "ec:k,m") and the current topology must be able to host it. The
// change affects new writes cluster-wide within seconds; existing objects convert through
// repair/rebalance. Returns the effective scheme after applying. Returns 400 when the scheme is
// invalid or the topology cannot host it, 404 when the bucket does not exist and 501 when the server
// is not in cluster mode.
//
// PUT /api/v1/buckets/{bucket}/scheme
func (c *Client) SetBucketScheme(ctx context.Context, request *SetBucketSchemeRequest, params SetBucketSchemeParams) (*BucketScheme, error) {
	res, err := c.sendSetBucketScheme(ctx, request, params)
	return res, err
}

func (c *Client) sendSetBucketScheme(ctx context.Context, request *SetBucketSchemeRequest, params SetBucketSchemeParams) (res *BucketScheme, err error) {
	otelAttrs := []attribute.KeyValue{
		otelogen.OperationID("setBucketScheme"),
		semconv.HTTPRequestMethodKey.String("PUT"),
		semconv.URLTemplateKey.String("/api/v1/buckets/{bucket}/scheme"),
	}
	otelAttrs = append(otelAttrs, c.cfg.Attributes...)

	// Run stopwatch.
	startTime := time.Now()
	defer func() {
		// Use floating point division here for higher precision (instead of Millisecond method).
		elapsedDuration := time.Since(startTime)
		c.duration.Record(ctx, float64(elapsedDuration)/float64(time.Millisecond), metric.WithAttributes(otelAttrs...))
	}()

	// Increment request counter.
	c.requests.Add(ctx, 1, metric.WithAttributes(otelAttrs...))

	// Start a span for this request.
	ctx, span := c.cfg.Tracer.Start(ctx, SetBucketSchemeOperation,
		trace.WithAttributes(otelAttrs...),
		clientSpanKind,
	)
	// Track stage for error reporting.
	var stage string
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, stage)
			c.errors.Add(ctx, 1, metric.WithAttributes(otelAttrs...))
		}
		span.End()
	}()

	stage = "BuildURL"
	u := uri.Clone(c.requestURL(ctx))
	var pathParts [3]string
	pathParts[0] = "/api/v1/buckets/"
	{
		// Encode "bucket" parameter.
		e := uri.NewPathEncoder(uri.PathEncoderConfig{
			Param:   "bucket",
			Style:   uri.PathStyleSimple,
			Explode: false,
		})
		if err := func() error {
			return e.EncodeValue(conv.StringToString(params.Bucket))
		}(); err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		encoded, err := e.Result()
		if err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		pathParts[1] = encoded
	}
	pathParts[2] = "/scheme"
	uri.AddPathParts(u, pathParts[:]...)

	stage = "EncodeRequest"
	r, err := ht.NewRequest(ctx, "PUT", u)
	if err != nil {
		return res, errors.Wrap(err, "create request")
	}
	if err := encodeSetBucketSchemeRequest(request, r); err != nil {
		return res, errors.Wrap(err, "encode request")
	}

	stage = "SendRequest"
	resp, err := c.cfg.Client.Do(r)
	if err != nil {
		return res, errors.Wrap(err, "do request")
	}
	body := resp.Body
	defer func() {
		// Drain the body to EOF before closing, so the underlying
		// connection can be reused by the Transport regardless of the
		// response status code. See https://github.com/ogen-go/ogen/issues/1670.
		_, _ = io.Copy(io.Discard, body)
		_ = body.Close()
	}()

	stage = "DecodeResponse"
	result, err := decodeSetBucketSchemeResponse(resp)
	if err != nil {
		return res, errors.Wrap(err, "decode response")
	}

	return result, nil
}

// SetDiskWeight invokes setDiskWeight operation.
//
// Set the weight placement uses for one disk, until it is cleared. A weight that is not positive
// drains the disk: no new data is placed on it and the auto-rebalancer moves what it holds elsewhere.
// The override lives outside the node's registration, so a node republishing its record — which it
// does on every capacity refresh and every restart — does not undo it. Accepted while the node is
// down: the moment an operator most wants to drain a disk is often the moment it is unreachable. An
// override for a disk that never appears is inert. Returns 501 when the server is not in cluster mode.
//
// PUT /api/v1/cluster/disk-weights/{node}/{disk}
func (c *Client) SetDiskWeight(ctx context.Context, request *SetDiskWeightRequest, params SetDiskWeightParams) (*DiskWeight, error) {
	res, err := c.sendSetDiskWeight(ctx, request, params)
	return res, err
}

func (c *Client) sendSetDiskWeight(ctx context.Context, request *SetDiskWeightRequest, params SetDiskWeightParams) (res *DiskWeight, err error) {
	otelAttrs := []attribute.KeyValue{
		otelogen.OperationID("setDiskWeight"),
		semconv.HTTPRequestMethodKey.String("PUT"),
		semconv.URLTemplateKey.String("/api/v1/cluster/disk-weights/{node}/{disk}"),
	}
	otelAttrs = append(otelAttrs, c.cfg.Attributes...)

	// Run stopwatch.
	startTime := time.Now()
	defer func() {
		// Use floating point division here for higher precision (instead of Millisecond method).
		elapsedDuration := time.Since(startTime)
		c.duration.Record(ctx, float64(elapsedDuration)/float64(time.Millisecond), metric.WithAttributes(otelAttrs...))
	}()

	// Increment request counter.
	c.requests.Add(ctx, 1, metric.WithAttributes(otelAttrs...))

	// Start a span for this request.
	ctx, span := c.cfg.Tracer.Start(ctx, SetDiskWeightOperation,
		trace.WithAttributes(otelAttrs...),
		clientSpanKind,
	)
	// Track stage for error reporting.
	var stage string
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, stage)
			c.errors.Add(ctx, 1, metric.WithAttributes(otelAttrs...))
		}
		span.End()
	}()

	stage = "BuildURL"
	u := uri.Clone(c.requestURL(ctx))
	var pathParts [4]string
	pathParts[0] = "/api/v1/cluster/disk-weights/"
	{
		// Encode "node" parameter.
		e := uri.NewPathEncoder(uri.PathEncoderConfig{
			Param:   "node",
			Style:   uri.PathStyleSimple,
			Explode: false,
		})
		if err := func() error {
			return e.EncodeValue(conv.StringToString(params.Node))
		}(); err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		encoded, err := e.Result()
		if err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		pathParts[1] = encoded
	}
	pathParts[2] = "/"
	{
		// Encode "disk" parameter.
		e := uri.NewPathEncoder(uri.PathEncoderConfig{
			Param:   "disk",
			Style:   uri.PathStyleSimple,
			Explode: false,
		})
		if err := func() error {
			return e.EncodeValue(conv.StringToString(params.Disk))
		}(); err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		encoded, err := e.Result()
		if err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		pathParts[3] = encoded
	}
	uri.AddPathParts(u, pathParts[:]...)

	stage = "EncodeRequest"
	r, err := ht.NewRequest(ctx, "PUT", u)
	if err != nil {
		return res, errors.Wrap(err, "create request")
	}
	if err := encodeSetDiskWeightRequest(request, r); err != nil {
		return res, errors.Wrap(err, "encode request")
	}

	stage = "SendRequest"
	resp, err := c.cfg.Client.Do(r)
	if err != nil {
		return res, errors.Wrap(err, "do request")
	}
	body := resp.Body
	defer func() {
		// Drain the body to EOF before closing, so the underlying
		// connection can be reused by the Transport regardless of the
		// response status code. See https://github.com/ogen-go/ogen/issues/1670.
		_, _ = io.Copy(io.Discard, body)
		_ = body.Close()
	}()

	stage = "DecodeResponse"
	result, err := decodeSetDiskWeightResponse(resp)
	if err != nil {
		return res, errors.Wrap(err, "decode response")
	}

	return result, nil
}

// SetPublicReadBuckets invokes setPublicReadBuckets operation.
//
// Replace the cluster-wide public-read bucket list. The change propagates to every node within seconds
// with no restart. Returns the stored list. Returns 400 on an invalid bucket name and 501 when not
// using cluster-wide credentials.
//
// PUT /api/v1/public-read-buckets
func (c *Client) SetPublicReadBuckets(ctx context.Context, request *SetPublicReadBucketsRequest) (*PublicReadBuckets, error) {
	res, err := c.sendSetPublicReadBuckets(ctx, request)
	return res, err
}

func (c *Client) sendSetPublicReadBuckets(ctx context.Context, request *SetPublicReadBucketsRequest) (res *PublicReadBuckets, err error) {
	otelAttrs := []attribute.KeyValue{
		otelogen.OperationID("setPublicReadBuckets"),
		semconv.HTTPRequestMethodKey.String("PUT"),
		semconv.URLTemplateKey.String("/api/v1/public-read-buckets"),
	}
	otelAttrs = append(otelAttrs, c.cfg.Attributes...)

	// Run stopwatch.
	startTime := time.Now()
	defer func() {
		// Use floating point division here for higher precision (instead of Millisecond method).
		elapsedDuration := time.Since(startTime)
		c.duration.Record(ctx, float64(elapsedDuration)/float64(time.Millisecond), metric.WithAttributes(otelAttrs...))
	}()

	// Increment request counter.
	c.requests.Add(ctx, 1, metric.WithAttributes(otelAttrs...))

	// Start a span for this request.
	ctx, span := c.cfg.Tracer.Start(ctx, SetPublicReadBucketsOperation,
		trace.WithAttributes(otelAttrs...),
		clientSpanKind,
	)
	// Track stage for error reporting.
	var stage string
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, stage)
			c.errors.Add(ctx, 1, metric.WithAttributes(otelAttrs...))
		}
		span.End()
	}()

	stage = "BuildURL"
	u := uri.Clone(c.requestURL(ctx))
	var pathParts [1]string
	pathParts[0] = "/api/v1/public-read-buckets"
	uri.AddPathParts(u, pathParts[:]...)

	stage = "EncodeRequest"
	r, err := ht.NewRequest(ctx, "PUT", u)
	if err != nil {
		return res, errors.Wrap(err, "create request")
	}
	if err := encodeSetPublicReadBucketsRequest(request, r); err != nil {
		return res, errors.Wrap(err, "encode request")
	}

	stage = "SendRequest"
	resp, err := c.cfg.Client.Do(r)
	if err != nil {
		return res, errors.Wrap(err, "do request")
	}
	body := resp.Body
	defer func() {
		// Drain the body to EOF before closing, so the underlying
		// connection can be reused by the Transport regardless of the
		// response status code. See https://github.com/ogen-go/ogen/issues/1670.
		_, _ = io.Copy(io.Discard, body)
		_ = body.Close()
	}()

	stage = "DecodeResponse"
	result, err := decodeSetPublicReadBucketsResponse(resp)
	if err != nil {
		return res, errors.Wrap(err, "decode response")
	}

	return result, nil
}
