// Command gencompat generates docs/CONFORMANCE.md from the ceph/s3-tests
// known-failures list, grouping the remaining gaps by feature area.
//
// The gate is a deny-list, so the repository states what does *not* pass and CI
// holds everything else to passing. This document is the human-readable view of
// that list and must be regenerated whenever it changes (see `make compat`).
package main

import (
	"bufio"
	"fmt"
	"os"
	"regexp"
	"sort"
	"strings"
)

const (
	knownPath = ".github/s3tests/known-failures.txt"
	outPath   = "docs/CONFORMANCE.md"
)

// category is a feature area and the ordered rules that assign a test to it. The
// first category whose regexp matches a test name wins, so order matters:
// more specific areas come before the broad object/bucket buckets.
type category struct {
	name string
	re   *regexp.Regexp
}

var categories = []category{
	{"Multipart upload", regexp.MustCompile(`multipart|upload_part|_mp_|list_parts`)},
	{"Object tagging", regexp.MustCompile(`_tag|tagging`)},
	{"Object metadata", regexp.MustCompile(`metadata|cache_control|content.type|_atomic_|atomic_`)},
	{"Server-side copy", regexp.MustCompile(`_copy|copy_`)},
	{"Conditional requests", regexp.MustCompile(`if_?match|if_?none|ifmatch|ifnonematch|ifmodified|ifunmodified|conditional`)},
	{"Ranged reads", regexp.MustCompile(`ranged|_range`)},
	{"Encryption passthrough", regexp.MustCompile(`_enc|encrypt|sse`)},
	{"HTTP protocol", regexp.MustCompile(`100_continue|error_retry|requestid|request_id`)},
	{"Bucket listing", regexp.MustCompile(`_list|listv2|key_count|delimiter|marker|maxkeys|continuation|startafter|fetchowner`)},
	{"Bucket lifecycle", regexp.MustCompile(`bucket|buckets_|bucketv2`)},
	{"Object CRUD", regexp.MustCompile(`object|obj_|delete|_key`)},
}

func categorize(test string) string {
	for _, c := range categories {
		if c.re.MatchString(test) {
			return c.name
		}
	}

	return "Other"
}

func main() {
	if err := run(); err != nil {
		fmt.Fprintln(os.Stderr, "gencompat:", err)
		os.Exit(1)
	}
}

func run() error {
	tests, err := readList(knownPath)
	if err != nil {
		return err
	}

	counts := make(map[string]int)
	for _, t := range tests {
		counts[categorize(t)]++
	}

	// Emit categories in their declared order, then Other last if non-empty.
	var rows [][2]string

	total := 0

	for _, c := range categories {
		if n := counts[c.name]; n > 0 {
			rows = append(rows, [2]string{c.name, fmt.Sprint(n)})
			total += n
		}
	}

	if n := counts["Other"]; n > 0 {
		rows = append(rows, [2]string{"Other", fmt.Sprint(n)})
		total += n
	}

	return writeDoc(outPath, rows, total, len(tests))
}

// readList returns the sorted, de-duplicated test node IDs from a list,
// ignoring blank and comment lines.
func readList(path string) ([]string, error) {
	f, err := os.Open(path) //nolint:gosec // Fixed repo-relative path.
	if err != nil {
		return nil, err
	}
	defer func() { _ = f.Close() }()

	seen := make(map[string]struct{})

	var tests []string

	sc := bufio.NewScanner(f)
	for sc.Scan() {
		line := strings.TrimSpace(sc.Text())
		if i := strings.IndexByte(line, '#'); i >= 0 {
			line = strings.TrimSpace(line[:i])
		}

		if line == "" {
			continue
		}

		if _, ok := seen[line]; ok {
			continue
		}

		seen[line] = struct{}{}

		tests = append(tests, line)
	}

	if err := sc.Err(); err != nil {
		return nil, err
	}

	sort.Strings(tests)

	return tests, nil
}

func writeDoc(path string, rows [][2]string, total, count int) error {
	var b strings.Builder

	b.WriteString("<!-- Generated by `make compat` from .github/s3tests/known-failures.txt. Do not edit by hand. -->\n\n")
	b.WriteString("# S3 conformance\n\n")
	b.WriteString("Every pull request runs the **whole** upstream\n")
	b.WriteString("[ceph/s3-tests](https://github.com/ceph/s3-tests) suite — the objective,\n")
	b.WriteString("client-driven measure of S3 compatibility — and fails if any test outside the\n")
	fmt.Fprintf(&b, "known-failures list fails, or if any of the **%d** tests inside it passes.\n", count)
	b.WriteString("The list can therefore only shrink; a newly passing test shows up on the pull\n")
	b.WriteString("request that made it pass, rather than waiting to be noticed.\n\n")
	b.WriteString("What follows is that list, grouped. Everything else in the suite passes.\n\n")

	b.WriteString("## Remaining gaps by feature area\n\n")
	b.WriteString("| Feature area | Tests not passing |\n")
	b.WriteString("|--------------|------------------:|\n")

	for _, r := range rows {
		fmt.Fprintf(&b, "| %s | %s |\n", r[0], r[1])
	}

	fmt.Fprintf(&b, "| **Total** | **%d** |\n\n", total)

	b.WriteString("## SDK & client coverage\n\n")
	b.WriteString("Beyond ceph/s3-tests, the server is exercised end-to-end through real S3\n")
	b.WriteString("clients:\n\n")
	b.WriteString("| Client | How |\n")
	b.WriteString("|--------|-----|\n")
	b.WriteString("| [minio-go](https://github.com/minio/minio-go) | in-process integration tests (`integration/`) |\n")
	b.WriteString("| [aws-sdk-go-v2](https://github.com/aws/aws-sdk-go-v2) | in-process integration tests (`integration/`) |\n")
	b.WriteString("| aws-cli, MinIO `mc`, `s3cmd`, `rclone` | live-binary smoke matrix (`scripts/cli-smoke.sh`, CI-gated) |\n\n")

	b.WriteString("Custom `fs.Storage` backends inherit the behavioral contract via the\n")
	b.WriteString("[`storagetest`](../storagetest) conformance suite.\n")

	return os.WriteFile(path, []byte(b.String()), 0o644) //nolint:gosec // Generated doc, world-readable is intended.
}
