// Command gencompat generates docs/CONFORMANCE.md from the ceph/s3-tests
// allow-list, grouping the passing tests by feature area. The allow-list is the
// authoritative compatibility statement; this table is a human-readable view of
// it and must be regenerated whenever the list changes (see `make compat`).
package main

import (
	"bufio"
	"fmt"
	"os"
	"regexp"
	"sort"
	"strings"
)

const (
	allowPath = ".github/s3tests/allow.txt"
	outPath   = "docs/CONFORMANCE.md"
)

// category is a feature area and the ordered rules that assign a test to it. The
// first category whose regexp matches a test name wins, so order matters:
// more specific areas come before the broad object/bucket buckets.
type category struct {
	name string
	re   *regexp.Regexp
}

var categories = []category{
	{"Multipart upload", regexp.MustCompile(`multipart|upload_part|_mp_|list_parts`)},
	{"Object tagging", regexp.MustCompile(`_tag|tagging`)},
	{"Object metadata", regexp.MustCompile(`metadata|cache_control|content.type|_atomic_|atomic_`)},
	{"Server-side copy", regexp.MustCompile(`_copy|copy_`)},
	{"Conditional requests", regexp.MustCompile(`if_?match|if_?none|ifmatch|ifnonematch|ifmodified|ifunmodified|conditional`)},
	{"Ranged reads", regexp.MustCompile(`ranged|_range`)},
	{"Encryption passthrough", regexp.MustCompile(`_enc|encrypt|sse`)},
	{"HTTP protocol", regexp.MustCompile(`100_continue|error_retry|requestid|request_id`)},
	{"Bucket listing", regexp.MustCompile(`_list|listv2|key_count|delimiter|marker|maxkeys|continuation|startafter|fetchowner`)},
	{"Bucket lifecycle", regexp.MustCompile(`bucket|buckets_|bucketv2`)},
	{"Object CRUD", regexp.MustCompile(`object|obj_|delete|_key`)},
}

func categorize(test string) string {
	for _, c := range categories {
		if c.re.MatchString(test) {
			return c.name
		}
	}

	return "Other"
}

func main() {
	if err := run(); err != nil {
		fmt.Fprintln(os.Stderr, "gencompat:", err)
		os.Exit(1)
	}
}

func run() error {
	tests, err := readAllow(allowPath)
	if err != nil {
		return err
	}

	counts := make(map[string]int)
	for _, t := range tests {
		counts[categorize(t)]++
	}

	// Emit categories in their declared order, then Other last if non-empty.
	var rows [][2]string

	total := 0

	for _, c := range categories {
		if n := counts[c.name]; n > 0 {
			rows = append(rows, [2]string{c.name, fmt.Sprint(n)})
			total += n
		}
	}

	if n := counts["Other"]; n > 0 {
		rows = append(rows, [2]string{"Other", fmt.Sprint(n)})
		total += n
	}

	return writeDoc(outPath, rows, total, len(tests))
}

// readAllow returns the sorted, de-duplicated test node IDs from the allow-list,
// ignoring blank and comment lines.
func readAllow(path string) ([]string, error) {
	f, err := os.Open(path) //nolint:gosec // Fixed repo-relative path.
	if err != nil {
		return nil, err
	}
	defer func() { _ = f.Close() }()

	seen := make(map[string]struct{})

	var tests []string

	sc := bufio.NewScanner(f)
	for sc.Scan() {
		line := strings.TrimSpace(sc.Text())
		if i := strings.IndexByte(line, '#'); i >= 0 {
			line = strings.TrimSpace(line[:i])
		}

		if line == "" {
			continue
		}

		if _, ok := seen[line]; ok {
			continue
		}

		seen[line] = struct{}{}

		tests = append(tests, line)
	}

	if err := sc.Err(); err != nil {
		return nil, err
	}

	sort.Strings(tests)

	return tests, nil
}

func writeDoc(path string, rows [][2]string, total, count int) error {
	var b strings.Builder

	b.WriteString("<!-- Generated by `make compat` from .github/s3tests/allow.txt. Do not edit by hand. -->\n\n")
	b.WriteString("# S3 conformance\n\n")
	fmt.Fprintf(&b, "`go-faster/fs` is gated in CI against **%d** tests from the upstream\n", count)
	b.WriteString("[ceph/s3-tests](https://github.com/ceph/s3-tests) suite — the objective,\n")
	b.WriteString("client-driven measure of S3 compatibility. Every pull request runs this exact\n")
	b.WriteString("set and fails if any test regresses. The list only grows as features land.\n\n")

	b.WriteString("## Conformance by feature area\n\n")
	b.WriteString("| Feature area | Passing conformance tests |\n")
	b.WriteString("|--------------|--------------------------:|\n")

	for _, r := range rows {
		fmt.Fprintf(&b, "| %s | %s |\n", r[0], r[1])
	}

	fmt.Fprintf(&b, "| **Total** | **%d** |\n\n", total)

	b.WriteString("## SDK & client coverage\n\n")
	b.WriteString("Beyond ceph/s3-tests, the server is exercised end-to-end through real S3\n")
	b.WriteString("clients:\n\n")
	b.WriteString("| Client | How |\n")
	b.WriteString("|--------|-----|\n")
	b.WriteString("| [minio-go](https://github.com/minio/minio-go) | in-process integration tests (`integration/`) |\n")
	b.WriteString("| [aws-sdk-go-v2](https://github.com/aws/aws-sdk-go-v2) | in-process integration tests (`integration/`) |\n")
	b.WriteString("| aws-cli, MinIO `mc`, `s3cmd`, `rclone` | live-binary smoke matrix (`scripts/cli-smoke.sh`, CI-gated) |\n\n")

	b.WriteString("Custom `fs.Storage` backends inherit the behavioral contract via the\n")
	b.WriteString("[`storagetest`](../storagetest) conformance suite.\n")

	return os.WriteFile(path, []byte(b.String()), 0o644) //nolint:gosec // Generated doc, world-readable is intended.
}
