services:
  fs:
    build:
      context: ..
      dockerfile: Dockerfile
    command:
      - s3
      - --addr
      - :8080
      - --root
      - /data/
    ports:
      - "127.0.0.1:8080:8080"
    tmpfs:
      - /data
    restart: unless-stopped
    environment:
      OTEL_EXPORTER_PROMETHEUS_HOST: 0.0.0.0
      OTEL_EXPORTER_PROMETHEUS_PORT: 9464
      OTEL_TRACES_EXPORTER: otlp
      OTEL_EXPORTER_OTLP_TRACES_ENDPOINT: http://jaeger:4317
      OTEL_LOGS_EXPORTER: none
      OTEL_LOG_LEVEL: debug
      OTEL_METRICS_EXPORTER: prometheus
      PPROF_ADDR: 0.0.0.0:9090

    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8080", "||", "exit", "1"]
      interval: 5s
      timeout: 5s
      retries: 3
      start_period: 1s

  jaeger:
    image: jaegertracing/all-in-one:latest

  tempo:
    image: grafana/tempo:latest
    depends_on:
      - redpanda
    command: "-target=all -config.file=/etc/tempo.yaml"
    restart: always
    volumes:
      - ./tempo.yml:/etc/tempo.yaml
    tmpfs:
      - /var/tempo:mode=0777
    ports:
      - "3200:3200" # tempo
      - "4317:4317" # Tempo OTLP GRPC
      - "4318:4318" # Tempo OTLP HTTP
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://alloy:4318

  # ingest pipeline
  k6-tracing:
    image: ghcr.io/grafana/xk6-client-tracing:v0.0.9
    environment:
      - ENDPOINT=alloy:4317
    restart: always
    depends_on:
      - tempo
      - alloy

  alloy:
    image: grafana/alloy:v1.12.2@sha256:f94b1c82957accb77cd11385fd5e3600758ef1b1ab79557c97319ad28590735a
    volumes:
      - ./config.alloy:/etc/alloy/config.alloy
    command:
      - run
      - /etc/alloy/config.alloy
      - --storage.path=/var/lib/alloy/data
      - --server.http.listen-addr=0.0.0.0:12345
    environment:
      - ALLOY_OTLP_UPSTREAM=tempo:4317
    ports:
      - "12345:12345"
      - "4319:4317"
    depends_on:
      - tempo

  redpanda:
    image: redpandadata/redpanda:latest
    command: >
      redpanda start --overprovisioned
      --mode=dev-container
      --kafka-addr=PLAINTEXT://0.0.0.0:9092
      --advertise-kafka-addr=PLAINTEXT://redpanda:9092

  redpanda-console:
    image: docker.redpanda.com/redpandadata/console:v3.5.0@sha256:b2cbdd93dee412142f95a61488118f33b8e31ea576bfb3ce625fbaffbdf0803a
    environment:
      - CONFIG_FILEPATH=/etc/redpanda/redpanda-console-config.yaml
    volumes:
      - ./redpanda-console.yml:/etc/redpanda/redpanda-console-config.yaml
    ports:
      - "3300:8080"
    depends_on:
      - redpanda

  # supporting services - metrics, visualization and testing
  prometheus:
    image: prom/prometheus:latest
    command:
      - --config.file=/etc/prometheus.yaml
      - --web.enable-remote-write-receiver
      - --enable-feature=exemplar-storage
      - --enable-feature=native-histograms
    volumes:
      - ./prometheus.yml:/etc/prometheus.yaml
    ports:
      - "9090:9090"

  vulture:
    image: grafana/tempo-vulture:latest
    restart: always
    command:
      [
        "-prometheus-listen-address=:8080",
        "-tempo-query-url=http://tempo:3200",
        "-tempo-push-url=http://tempo:4317",
      ]
    depends_on:
      - tempo

  grafana:
    image: "grafana/grafana:12.3"
    restart: unless-stopped
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
      - GF_ALERTING_ENABLED=false
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_LOG_LEVEL=warn
    depends_on:
      - tempo
    ports:
      - "127.0.0.1:3000:3000"
    volumes:
      - ./grafana/datasources.yml:/etc/grafana/provisioning/datasources/datasources.yml
      - ./grafana/dashboards.yml:/etc/grafana/provisioning/dashboards/default.yml
      - ./grafana/dashboards:/etc/grafana/dashboards:ro
