/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * go-faster/fs admin API
 * Administrative API for a go-faster/fs S3 server: instance info and runtime management of access keys (create, list and delete credentials without a restart). Intended to be served on a separate, authenticated admin listener.

 * OpenAPI spec version: 0.1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  AccessKeyList,
  CreateAccessKeyRequest,
  CreatedAccessKey,
  ErrorResponse,
  InstanceInfo,
  RebalanceControlRequest,
  RebalanceStatus
} from './model';

import { customFetch } from '../lib/fetcher';




/**
 * Build information, uptime and whether authentication is enabled.
 * @summary Instance info
 */
export const getInfo = (
    
 signal?: AbortSignal
) => {
      
      
      return customFetch<InstanceInfo>(
      {url: `/api/v1/info`, method: 'GET', signal
    },
      );
    }
  



export const getGetInfoQueryKey = () => {
    return [
    `/api/v1/info`
    ] as const;
    }

    
export const getGetInfoQueryOptions = <TData = Awaited<ReturnType<typeof getInfo>>, TError = ErrorResponse>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getInfo>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetInfoQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getInfo>>> = ({ signal }) => getInfo(signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getInfo>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetInfoQueryResult = NonNullable<Awaited<ReturnType<typeof getInfo>>>
export type GetInfoQueryError = ErrorResponse


export function useGetInfo<TData = Awaited<ReturnType<typeof getInfo>>, TError = ErrorResponse>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getInfo>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getInfo>>,
          TError,
          Awaited<ReturnType<typeof getInfo>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetInfo<TData = Awaited<ReturnType<typeof getInfo>>, TError = ErrorResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getInfo>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getInfo>>,
          TError,
          Awaited<ReturnType<typeof getInfo>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetInfo<TData = Awaited<ReturnType<typeof getInfo>>, TError = ErrorResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getInfo>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Instance info
 */

export function useGetInfo<TData = Awaited<ReturnType<typeof getInfo>>, TError = ErrorResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getInfo>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetInfoQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}





/**
 * Every credential the server accepts, secrets omitted.
 * @summary List access keys
 */
export const listAccessKeys = (
    
 signal?: AbortSignal
) => {
      
      
      return customFetch<AccessKeyList>(
      {url: `/api/v1/access-keys`, method: 'GET', signal
    },
      );
    }
  



export const getListAccessKeysQueryKey = () => {
    return [
    `/api/v1/access-keys`
    ] as const;
    }

    
export const getListAccessKeysQueryOptions = <TData = Awaited<ReturnType<typeof listAccessKeys>>, TError = ErrorResponse>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listAccessKeys>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListAccessKeysQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof listAccessKeys>>> = ({ signal }) => listAccessKeys(signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listAccessKeys>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListAccessKeysQueryResult = NonNullable<Awaited<ReturnType<typeof listAccessKeys>>>
export type ListAccessKeysQueryError = ErrorResponse


export function useListAccessKeys<TData = Awaited<ReturnType<typeof listAccessKeys>>, TError = ErrorResponse>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listAccessKeys>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listAccessKeys>>,
          TError,
          Awaited<ReturnType<typeof listAccessKeys>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListAccessKeys<TData = Awaited<ReturnType<typeof listAccessKeys>>, TError = ErrorResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listAccessKeys>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listAccessKeys>>,
          TError,
          Awaited<ReturnType<typeof listAccessKeys>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListAccessKeys<TData = Awaited<ReturnType<typeof listAccessKeys>>, TError = ErrorResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listAccessKeys>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List access keys
 */

export function useListAccessKeys<TData = Awaited<ReturnType<typeof listAccessKeys>>, TError = ErrorResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listAccessKeys>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListAccessKeysQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}





/**
 * Create a runtime credential. The access key and secret are generated when not supplied. The secret is returned only in this response and cannot be retrieved later.

 * @summary Create an access key
 */
export const createAccessKey = (
    createAccessKeyRequest: CreateAccessKeyRequest,
 signal?: AbortSignal
) => {
      
      
      return customFetch<CreatedAccessKey>(
      {url: `/api/v1/access-keys`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createAccessKeyRequest, signal
    },
      );
    }
  


export const getCreateAccessKeyMutationOptions = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createAccessKey>>, TError,{data: CreateAccessKeyRequest}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof createAccessKey>>, TError,{data: CreateAccessKeyRequest}, TContext> => {

const mutationKey = ['createAccessKey'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createAccessKey>>, {data: CreateAccessKeyRequest}> = (props) => {
          const {data} = props ?? {};

          return  createAccessKey(data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type CreateAccessKeyMutationResult = NonNullable<Awaited<ReturnType<typeof createAccessKey>>>
    export type CreateAccessKeyMutationBody = CreateAccessKeyRequest
    export type CreateAccessKeyMutationError = ErrorResponse

    /**
 * @summary Create an access key
 */
export const useCreateAccessKey = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createAccessKey>>, TError,{data: CreateAccessKeyRequest}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createAccessKey>>,
        TError,
        {data: CreateAccessKeyRequest},
        TContext
      > => {

      const mutationOptions = getCreateAccessKeyMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    
/**
 * State and progress of the cluster rebalance runner on this node, the persisted resume cursor and the depth of the async repair queue. State is "disabled" when the server is not in cluster mode.

 * @summary Cluster rebalance status
 */
export const getRebalanceStatus = (
    
 signal?: AbortSignal
) => {
      
      
      return customFetch<RebalanceStatus>(
      {url: `/api/v1/cluster/rebalance`, method: 'GET', signal
    },
      );
    }
  



export const getGetRebalanceStatusQueryKey = () => {
    return [
    `/api/v1/cluster/rebalance`
    ] as const;
    }

    
export const getGetRebalanceStatusQueryOptions = <TData = Awaited<ReturnType<typeof getRebalanceStatus>>, TError = ErrorResponse>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getRebalanceStatus>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetRebalanceStatusQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getRebalanceStatus>>> = ({ signal }) => getRebalanceStatus(signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getRebalanceStatus>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetRebalanceStatusQueryResult = NonNullable<Awaited<ReturnType<typeof getRebalanceStatus>>>
export type GetRebalanceStatusQueryError = ErrorResponse


export function useGetRebalanceStatus<TData = Awaited<ReturnType<typeof getRebalanceStatus>>, TError = ErrorResponse>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getRebalanceStatus>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getRebalanceStatus>>,
          TError,
          Awaited<ReturnType<typeof getRebalanceStatus>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetRebalanceStatus<TData = Awaited<ReturnType<typeof getRebalanceStatus>>, TError = ErrorResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getRebalanceStatus>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getRebalanceStatus>>,
          TError,
          Awaited<ReturnType<typeof getRebalanceStatus>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetRebalanceStatus<TData = Awaited<ReturnType<typeof getRebalanceStatus>>, TError = ErrorResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getRebalanceStatus>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Cluster rebalance status
 */

export function useGetRebalanceStatus<TData = Awaited<ReturnType<typeof getRebalanceStatus>>, TError = ErrorResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getRebalanceStatus>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetRebalanceStatusQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}





/**
 * Start, pause or resume the cluster-wide rebalance from this node. At most one rebalance runs cluster-wide (etcd election); starting on several nodes leaves the extras waiting as standby runners. Pausing stops this node's runner and keeps the resume cursor, so a later start/resume — on any node — continues where it left off.

 * @summary Control the cluster rebalance
 */
export const controlRebalance = (
    rebalanceControlRequest: RebalanceControlRequest,
 signal?: AbortSignal
) => {
      
      
      return customFetch<RebalanceStatus>(
      {url: `/api/v1/cluster/rebalance`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: rebalanceControlRequest, signal
    },
      );
    }
  


export const getControlRebalanceMutationOptions = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof controlRebalance>>, TError,{data: RebalanceControlRequest}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof controlRebalance>>, TError,{data: RebalanceControlRequest}, TContext> => {

const mutationKey = ['controlRebalance'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof controlRebalance>>, {data: RebalanceControlRequest}> = (props) => {
          const {data} = props ?? {};

          return  controlRebalance(data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type ControlRebalanceMutationResult = NonNullable<Awaited<ReturnType<typeof controlRebalance>>>
    export type ControlRebalanceMutationBody = RebalanceControlRequest
    export type ControlRebalanceMutationError = ErrorResponse

    /**
 * @summary Control the cluster rebalance
 */
export const useControlRebalance = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof controlRebalance>>, TError,{data: RebalanceControlRequest}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof controlRebalance>>,
        TError,
        {data: RebalanceControlRequest},
        TContext
      > => {

      const mutationOptions = getControlRebalanceMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    
/**
 * Remove a runtime credential. Config-defined credentials cannot be deleted.
 * @summary Delete an access key
 */
export const deleteAccessKey = (
    accessKey: string,
 ) => {
      
      
      return customFetch<void>(
      {url: `/api/v1/access-keys/${accessKey}`, method: 'DELETE'
    },
      );
    }
  


export const getDeleteAccessKeyMutationOptions = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteAccessKey>>, TError,{accessKey: string}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof deleteAccessKey>>, TError,{accessKey: string}, TContext> => {

const mutationKey = ['deleteAccessKey'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteAccessKey>>, {accessKey: string}> = (props) => {
          const {accessKey} = props ?? {};

          return  deleteAccessKey(accessKey,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteAccessKeyMutationResult = NonNullable<Awaited<ReturnType<typeof deleteAccessKey>>>
    
    export type DeleteAccessKeyMutationError = ErrorResponse

    /**
 * @summary Delete an access key
 */
export const useDeleteAccessKey = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteAccessKey>>, TError,{accessKey: string}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteAccessKey>>,
        TError,
        {accessKey: string},
        TContext
      > => {

      const mutationOptions = getDeleteAccessKeyMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    
