/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * go-faster/fs admin API
 * Administrative API for a go-faster/fs S3 server: instance info and runtime management of access keys (create, list and delete credentials without a restart). Intended to be served on a separate, authenticated admin listener.

 * OpenAPI spec version: 0.1.0
 */

/**
 * One bucket's object count and total size.
 */
export interface BucketUsage {
  bucket: string;
  /** How many objects the bucket holds. */
  objects: number;
  /** What those objects occupy, summed over their sizes. This is logical size, not what the cluster stores: replication and erasure coding multiply it on disk (see the scheme's overhead). */
  bytes: number;
  /** When an incremental change last moved these counters. */
  updated?: string;
  /** When a full recount last anchored them. Absent means the totals have only ever been maintained incrementally, so nothing has verified them against the objects themselves yet. */
  counted?: string;
}
