/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * go-faster/fs admin API
 * Administrative API for a go-faster/fs S3 server: instance info and runtime management of access keys (create, list and delete credentials without a restart). Intended to be served on a separate, authenticated admin listener.

 * OpenAPI spec version: 0.1.0
 */

export interface ClusterDisk {
  id: string;
  /** Relative placement weight; not positive means drained (out of placement). */
  weight: number;
  /** Reported filesystem size; 0 when the node has not reported capacity. */
  total_bytes?: number;
  free_bytes?: number;
  /** Used fraction (0..1); omitted when capacity is unknown. */
  fullness?: number;
  /** Whether the disk still holds any fragment, as the node itself reports it. False means drained: its data has been moved off and the volume can be deleted. Omitted when the node did not report live state, or could not probe the disk (see data_error) — absent means unknown, never drained. Capacity cannot answer this, since it comes from statfs: a disk holding no fragments still reports bytes used. */
  has_data?: boolean;
  /** Why the disk could not be probed; has_data is then absent. */
  data_error?: string;
}
