/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * go-faster/fs admin API
 * Administrative API for a go-faster/fs S3 server: instance info and runtime management of access keys (create, list and delete credentials without a restart). Intended to be served on a separate, authenticated admin listener.

 * OpenAPI spec version: 0.1.0
 */
import type { RebalanceState } from './rebalanceState';

/**
 * A node's live runtime state, fetched from the node itself over the peer transport — what only the running process knows, as opposed to the control-plane state in etcd.

 */
export interface ClusterNodeLive {
  /** The node's binary version — a half-upgraded cluster shows mixed values. */
  version?: string;
  /** Schema version the node's binary implements. */
  schema_version?: number;
  uptime_seconds?: number;
  /** Objects with pending async replication/repair work on the node. */
  repair_queue_depth: number;
  rebalance_state: RebalanceState;
  rebalance_objects: number;
  rebalance_relocated: number;
  rebalance_failed: number;
  rebalance_error?: string;
  scrub_passes: number;
  scrub_objects: number;
  scrub_repaired: number;
  scrub_failed: number;
  /** Fragments rebuilt by scrubs on the node (repair lag indicator). */
  rebuilt_fragments: number;
  swept_stale: number;
  /** Replica payloads that failed checksum verification (bit-rot). */
  corrupt_replicas: number;
  /** Objects rewritten to their bucket's current scheme. */
  converted_objects: number;
  /** How many objects this node holds, as its own index counts them. Absent when the node could not derive it — a missing or still building index — which is not the same as holding none. */
  objects_held?: number;
  /** How many of them the scrub has never checked. Present alongside objects_held. */
  never_verified?: number;
  /** When the least recently checked object was checked. With never_verified at zero this is the age of the node's scrub coverage: every object it holds has been verified at least since then. Counts of scrub work say how busy the scrubber was; this says whether it is keeping up, and a cycle falling behind shows as this receding. */
  oldest_verified?: string;
  /** The node's last scrub pass saw an EC set failing parity verification. */
  ec_unverified: boolean;
}
