/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * go-faster/fs admin API
 * Administrative API for a go-faster/fs S3 server: instance info and runtime management of access keys (create, list and delete credentials without a restart). Intended to be served on a separate, authenticated admin listener.

 * OpenAPI spec version: 0.1.0
 */

export interface InstanceInfo {
  version: string;
  commit: string;
  go_version: string;
  os: string;
  arch: string;
  start_time: string;
  uptime_seconds: number;
  /** Whether SigV4 authentication is enabled. */
  auth_enabled: boolean;
  /** Opaque marker echoed from the loaded config file's "revision" field, updated on reload. Empty when the config sets none. An orchestrator writes a revision into each node's config and reads it back here to confirm the node has applied that revision.
 */
  config_revision?: string;
}
