/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * go-faster/fs admin API
 * Administrative API for a go-faster/fs S3 server: instance info and runtime management of access keys (create, list and delete credentials without a restart). Intended to be served on a separate, authenticated admin listener.

 * OpenAPI spec version: 0.1.0
 */

/**
 * Why the plane is building, and what decides whether anything rebuilds it without being asked. "never-built" is a plane switched on over a cluster that already held objects — planned, so the walk is an operator's to schedule. "orphaned" is a failure that left a range with no copy of its data — not planned, and the cluster is degraded until it is rebuilt. "unspecified" is a reason nobody recorded, which is never acted on automatically.

 */
export type MetadataPlaneCause = typeof MetadataPlaneCause[keyof typeof MetadataPlaneCause];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const MetadataPlaneCause = {
  unspecified: 'unspecified',
  'never-built': 'never-built',
  orphaned: 'orphaned',
} as const;
