/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * go-faster/fs admin API
 * Administrative API for a go-faster/fs S3 server: instance info and runtime management of access keys (create, list and delete credentials without a restart). Intended to be served on a separate, authenticated admin listener.

 * OpenAPI spec version: 0.1.0
 */
import type { ClusterState } from './clusterState';
import type { Migration } from './migration';

/**
 * Cluster schema state and the migrations pending between cluster and binary.
 */
export interface MigrationStatus {
  state: ClusterState;
  /** Schema version the cluster has agreed on; 0 when none is recorded yet (no node has joined).
 */
  cluster_schema_version: number;
  /** Schema version this binary implements. */
  binary_schema_version: number;
  /** True when nothing is pending: the cluster is at the binary's schema version. */
  up_to_date: boolean;
  /** True while this process is applying migrations. */
  running: boolean;
  pending: Migration[];
  /** Versions applied by the most recent run on this process. */
  last_applied?: number[];
  /** Why the most recent run on this process failed. */
  last_error?: string;
}
