/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * go-faster/fs admin API
 * Administrative API for a go-faster/fs S3 server: instance info and runtime management of access keys (create, list and delete credentials without a restart). Intended to be served on a separate, authenticated admin listener.

 * OpenAPI spec version: 0.1.0
 */

/**
 * Runner state on this node: "disabled" (not cluster mode), "idle" (never started since boot), "waiting" (campaigning for the cluster-wide slot behind another runner), "running", "paused" (stopped by an operator, resume cursor kept), "done" (last run completed) or "failed" (last run aborted with an error).

 */
export type RebalanceState = typeof RebalanceState[keyof typeof RebalanceState];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const RebalanceState = {
  disabled: 'disabled',
  idle: 'idle',
  waiting: 'waiting',
  running: 'running',
  paused: 'paused',
  done: 'done',
  failed: 'failed',
} as const;
