/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * go-faster/fs admin API
 * Administrative API for a go-faster/fs S3 server: instance info and runtime management of access keys (create, list and delete credentials without a restart). Intended to be served on a separate, authenticated admin listener.

 * OpenAPI spec version: 0.1.0
 */

export type RebalanceAction = typeof RebalanceAction[keyof typeof RebalanceAction];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const RebalanceAction = {
  start: 'start',
  pause: 'pause',
  resume: 'resume',
} as const;
