/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * go-faster/fs admin API
 * Administrative API for a go-faster/fs S3 server: instance info and runtime management of access keys (create, list and delete credentials without a restart). Intended to be served on a separate, authenticated admin listener.

 * OpenAPI spec version: 0.1.0
 */
import type { RebalanceState } from './rebalanceState';

export interface RebalanceStatus {
  state: RebalanceState;
  /** Objects processed by the current or last run on this node. */
  objects: number;
  /** Objects the run changed (fragments moved, sidecars rewritten, old copies retired). */
  relocated: number;
  /** Objects whose repair errored; the run continues past them. */
  failed: number;
  /** Persisted resume cursor: everything up to and including (bucket, key) is done. */
  cursor_bucket?: string;
  cursor_key?: string;
  /** When the current or last run started on this node. */
  started_at?: string;
  /** When the last run ended on this node. */
  finished_at?: string;
  /** Why the last run failed, for state "failed". */
  error_message?: string;
  /** Pending async replication-remainder tasks on this node (repair backlog indicator). */
  repair_queue_depth: number;
}
