/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * go-faster/fs admin API
 * Administrative API for a go-faster/fs S3 server: instance info and runtime management of access keys (create, list and delete credentials without a restart). Intended to be served on a separate, authenticated admin listener.

 * OpenAPI spec version: 0.1.0
 */

export interface ReloadResult {
  /** What the reload applied: any of "credentials", "tls". */
  reloaded: string[];
  /** The config revision in effect after the reload (see InstanceInfo.config_revision). */
  config_revision?: string;
}
