/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * go-faster/fs admin API
 * Administrative API for a go-faster/fs S3 server: instance info and runtime management of access keys (create, list and delete credentials without a restart). Intended to be served on a separate, authenticated admin listener.

 * OpenAPI spec version: 0.1.0
 */

/**
 * Set or clear a bucket's replication-scheme override.
 */
export interface SetBucketSchemeRequest {
  /** The scheme override to apply, e.g. "rf3" or "ec:4,2". An empty string (or "default") clears the override, restoring the cluster default.
 */
  scheme?: string;
}
