/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * go-faster/fs admin API
 * Administrative API for a go-faster/fs S3 server: instance info and runtime management of access keys (create, list and delete credentials without a restart). Intended to be served on a separate, authenticated admin listener.

 * OpenAPI spec version: 0.1.0
 */

export interface SetDiskWeightRequest {
  /** The placement weight to use. Not positive drains the disk. Zero means zero here — unlike the config file, where an omitted weight and an explicit 0 are indistinguishable and 0 is read as "unset".
 */
  weight: number;
  /** Free text, carried back on reads. */
  reason?: string;
}
