// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mock

import (
	"context"
	"sync"

	"github.com/go-faster/fs"
)

// Ensure, that ServiceMock does implement fs.Service.
// If this is not the case, regenerate this file with moq.
var _ fs.Service = &ServiceMock{}

// ServiceMock is a mock implementation of fs.Service.
//
//	func TestSomethingThatUsesService(t *testing.T) {
//
//		// make and configure a mocked fs.Service
//		mockedService := &ServiceMock{
//			AbortMultipartUploadFunc: func(ctx context.Context, bucket string, key string, uploadID string) error {
//				panic("mock out the AbortMultipartUpload method")
//			},
//			CompleteMultipartUploadFunc: func(ctx context.Context, req *fs.CompleteMultipartUploadRequest) (*fs.CompleteMultipartUploadResponse, error) {
//				panic("mock out the CompleteMultipartUpload method")
//			},
//			CreateBucketFunc: func(ctx context.Context, bucket string) error {
//				panic("mock out the CreateBucket method")
//			},
//			CreateMultipartUploadFunc: func(ctx context.Context, bucket string, key string) (*fs.MultipartUpload, error) {
//				panic("mock out the CreateMultipartUpload method")
//			},
//			DeleteBucketFunc: func(ctx context.Context, bucket string) error {
//				panic("mock out the DeleteBucket method")
//			},
//			DeleteObjectFunc: func(ctx context.Context, bucket string, key string) error {
//				panic("mock out the DeleteObject method")
//			},
//			GetObjectFunc: func(ctx context.Context, bucket string, key string) (*fs.GetObjectResponse, error) {
//				panic("mock out the GetObject method")
//			},
//			ListBucketsFunc: func(ctx context.Context) ([]fs.Bucket, error) {
//				panic("mock out the ListBuckets method")
//			},
//			ListObjectsFunc: func(ctx context.Context, bucket string, prefix string) ([]fs.Object, error) {
//				panic("mock out the ListObjects method")
//			},
//			PutObjectFunc: func(ctx context.Context, req *fs.PutObjectRequest) error {
//				panic("mock out the PutObject method")
//			},
//			UploadPartFunc: func(ctx context.Context, req *fs.UploadPartRequest) (*fs.Part, error) {
//				panic("mock out the UploadPart method")
//			},
//		}
//
//		// use mockedService in code that requires fs.Service
//		// and then make assertions.
//
//	}
type ServiceMock struct {
	// AbortMultipartUploadFunc mocks the AbortMultipartUpload method.
	AbortMultipartUploadFunc func(ctx context.Context, bucket string, key string, uploadID string) error

	// CompleteMultipartUploadFunc mocks the CompleteMultipartUpload method.
	CompleteMultipartUploadFunc func(ctx context.Context, req *fs.CompleteMultipartUploadRequest) (*fs.CompleteMultipartUploadResponse, error)

	// CreateBucketFunc mocks the CreateBucket method.
	CreateBucketFunc func(ctx context.Context, bucket string) error

	// CreateMultipartUploadFunc mocks the CreateMultipartUpload method.
	CreateMultipartUploadFunc func(ctx context.Context, bucket string, key string) (*fs.MultipartUpload, error)

	// DeleteBucketFunc mocks the DeleteBucket method.
	DeleteBucketFunc func(ctx context.Context, bucket string) error

	// DeleteObjectFunc mocks the DeleteObject method.
	DeleteObjectFunc func(ctx context.Context, bucket string, key string) error

	// GetObjectFunc mocks the GetObject method.
	GetObjectFunc func(ctx context.Context, bucket string, key string) (*fs.GetObjectResponse, error)

	// ListBucketsFunc mocks the ListBuckets method.
	ListBucketsFunc func(ctx context.Context) ([]fs.Bucket, error)

	// ListObjectsFunc mocks the ListObjects method.
	ListObjectsFunc func(ctx context.Context, bucket string, prefix string) ([]fs.Object, error)

	// PutObjectFunc mocks the PutObject method.
	PutObjectFunc func(ctx context.Context, req *fs.PutObjectRequest) error

	// UploadPartFunc mocks the UploadPart method.
	UploadPartFunc func(ctx context.Context, req *fs.UploadPartRequest) (*fs.Part, error)

	// calls tracks calls to the methods.
	calls struct {
		// AbortMultipartUpload holds details about calls to the AbortMultipartUpload method.
		AbortMultipartUpload []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Bucket is the bucket argument value.
			Bucket string
			// Key is the key argument value.
			Key string
			// UploadID is the uploadID argument value.
			UploadID string
		}
		// CompleteMultipartUpload holds details about calls to the CompleteMultipartUpload method.
		CompleteMultipartUpload []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Req is the req argument value.
			Req *fs.CompleteMultipartUploadRequest
		}
		// CreateBucket holds details about calls to the CreateBucket method.
		CreateBucket []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Bucket is the bucket argument value.
			Bucket string
		}
		// CreateMultipartUpload holds details about calls to the CreateMultipartUpload method.
		CreateMultipartUpload []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Bucket is the bucket argument value.
			Bucket string
			// Key is the key argument value.
			Key string
		}
		// DeleteBucket holds details about calls to the DeleteBucket method.
		DeleteBucket []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Bucket is the bucket argument value.
			Bucket string
		}
		// DeleteObject holds details about calls to the DeleteObject method.
		DeleteObject []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Bucket is the bucket argument value.
			Bucket string
			// Key is the key argument value.
			Key string
		}
		// GetObject holds details about calls to the GetObject method.
		GetObject []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Bucket is the bucket argument value.
			Bucket string
			// Key is the key argument value.
			Key string
		}
		// ListBuckets holds details about calls to the ListBuckets method.
		ListBuckets []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
		// ListObjects holds details about calls to the ListObjects method.
		ListObjects []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Bucket is the bucket argument value.
			Bucket string
			// Prefix is the prefix argument value.
			Prefix string
		}
		// PutObject holds details about calls to the PutObject method.
		PutObject []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Req is the req argument value.
			Req *fs.PutObjectRequest
		}
		// UploadPart holds details about calls to the UploadPart method.
		UploadPart []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Req is the req argument value.
			Req *fs.UploadPartRequest
		}
	}
	lockAbortMultipartUpload    sync.RWMutex
	lockCompleteMultipartUpload sync.RWMutex
	lockCreateBucket            sync.RWMutex
	lockCreateMultipartUpload   sync.RWMutex
	lockDeleteBucket            sync.RWMutex
	lockDeleteObject            sync.RWMutex
	lockGetObject               sync.RWMutex
	lockListBuckets             sync.RWMutex
	lockListObjects             sync.RWMutex
	lockPutObject               sync.RWMutex
	lockUploadPart              sync.RWMutex
}

// AbortMultipartUpload calls AbortMultipartUploadFunc.
func (mock *ServiceMock) AbortMultipartUpload(ctx context.Context, bucket string, key string, uploadID string) error {
	if mock.AbortMultipartUploadFunc == nil {
		panic("ServiceMock.AbortMultipartUploadFunc: method is nil but Service.AbortMultipartUpload was just called")
	}
	callInfo := struct {
		Ctx      context.Context
		Bucket   string
		Key      string
		UploadID string
	}{
		Ctx:      ctx,
		Bucket:   bucket,
		Key:      key,
		UploadID: uploadID,
	}
	mock.lockAbortMultipartUpload.Lock()
	mock.calls.AbortMultipartUpload = append(mock.calls.AbortMultipartUpload, callInfo)
	mock.lockAbortMultipartUpload.Unlock()
	return mock.AbortMultipartUploadFunc(ctx, bucket, key, uploadID)
}

// AbortMultipartUploadCalls gets all the calls that were made to AbortMultipartUpload.
// Check the length with:
//
//	len(mockedService.AbortMultipartUploadCalls())
func (mock *ServiceMock) AbortMultipartUploadCalls() []struct {
	Ctx      context.Context
	Bucket   string
	Key      string
	UploadID string
} {
	var calls []struct {
		Ctx      context.Context
		Bucket   string
		Key      string
		UploadID string
	}
	mock.lockAbortMultipartUpload.RLock()
	calls = mock.calls.AbortMultipartUpload
	mock.lockAbortMultipartUpload.RUnlock()
	return calls
}

// CompleteMultipartUpload calls CompleteMultipartUploadFunc.
func (mock *ServiceMock) CompleteMultipartUpload(ctx context.Context, req *fs.CompleteMultipartUploadRequest) (*fs.CompleteMultipartUploadResponse, error) {
	if mock.CompleteMultipartUploadFunc == nil {
		panic("ServiceMock.CompleteMultipartUploadFunc: method is nil but Service.CompleteMultipartUpload was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Req *fs.CompleteMultipartUploadRequest
	}{
		Ctx: ctx,
		Req: req,
	}
	mock.lockCompleteMultipartUpload.Lock()
	mock.calls.CompleteMultipartUpload = append(mock.calls.CompleteMultipartUpload, callInfo)
	mock.lockCompleteMultipartUpload.Unlock()
	return mock.CompleteMultipartUploadFunc(ctx, req)
}

// CompleteMultipartUploadCalls gets all the calls that were made to CompleteMultipartUpload.
// Check the length with:
//
//	len(mockedService.CompleteMultipartUploadCalls())
func (mock *ServiceMock) CompleteMultipartUploadCalls() []struct {
	Ctx context.Context
	Req *fs.CompleteMultipartUploadRequest
} {
	var calls []struct {
		Ctx context.Context
		Req *fs.CompleteMultipartUploadRequest
	}
	mock.lockCompleteMultipartUpload.RLock()
	calls = mock.calls.CompleteMultipartUpload
	mock.lockCompleteMultipartUpload.RUnlock()
	return calls
}

// CreateBucket calls CreateBucketFunc.
func (mock *ServiceMock) CreateBucket(ctx context.Context, bucket string) error {
	if mock.CreateBucketFunc == nil {
		panic("ServiceMock.CreateBucketFunc: method is nil but Service.CreateBucket was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		Bucket string
	}{
		Ctx:    ctx,
		Bucket: bucket,
	}
	mock.lockCreateBucket.Lock()
	mock.calls.CreateBucket = append(mock.calls.CreateBucket, callInfo)
	mock.lockCreateBucket.Unlock()
	return mock.CreateBucketFunc(ctx, bucket)
}

// CreateBucketCalls gets all the calls that were made to CreateBucket.
// Check the length with:
//
//	len(mockedService.CreateBucketCalls())
func (mock *ServiceMock) CreateBucketCalls() []struct {
	Ctx    context.Context
	Bucket string
} {
	var calls []struct {
		Ctx    context.Context
		Bucket string
	}
	mock.lockCreateBucket.RLock()
	calls = mock.calls.CreateBucket
	mock.lockCreateBucket.RUnlock()
	return calls
}

// CreateMultipartUpload calls CreateMultipartUploadFunc.
func (mock *ServiceMock) CreateMultipartUpload(ctx context.Context, bucket string, key string) (*fs.MultipartUpload, error) {
	if mock.CreateMultipartUploadFunc == nil {
		panic("ServiceMock.CreateMultipartUploadFunc: method is nil but Service.CreateMultipartUpload was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		Bucket string
		Key    string
	}{
		Ctx:    ctx,
		Bucket: bucket,
		Key:    key,
	}
	mock.lockCreateMultipartUpload.Lock()
	mock.calls.CreateMultipartUpload = append(mock.calls.CreateMultipartUpload, callInfo)
	mock.lockCreateMultipartUpload.Unlock()
	return mock.CreateMultipartUploadFunc(ctx, bucket, key)
}

// CreateMultipartUploadCalls gets all the calls that were made to CreateMultipartUpload.
// Check the length with:
//
//	len(mockedService.CreateMultipartUploadCalls())
func (mock *ServiceMock) CreateMultipartUploadCalls() []struct {
	Ctx    context.Context
	Bucket string
	Key    string
} {
	var calls []struct {
		Ctx    context.Context
		Bucket string
		Key    string
	}
	mock.lockCreateMultipartUpload.RLock()
	calls = mock.calls.CreateMultipartUpload
	mock.lockCreateMultipartUpload.RUnlock()
	return calls
}

// DeleteBucket calls DeleteBucketFunc.
func (mock *ServiceMock) DeleteBucket(ctx context.Context, bucket string) error {
	if mock.DeleteBucketFunc == nil {
		panic("ServiceMock.DeleteBucketFunc: method is nil but Service.DeleteBucket was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		Bucket string
	}{
		Ctx:    ctx,
		Bucket: bucket,
	}
	mock.lockDeleteBucket.Lock()
	mock.calls.DeleteBucket = append(mock.calls.DeleteBucket, callInfo)
	mock.lockDeleteBucket.Unlock()
	return mock.DeleteBucketFunc(ctx, bucket)
}

// DeleteBucketCalls gets all the calls that were made to DeleteBucket.
// Check the length with:
//
//	len(mockedService.DeleteBucketCalls())
func (mock *ServiceMock) DeleteBucketCalls() []struct {
	Ctx    context.Context
	Bucket string
} {
	var calls []struct {
		Ctx    context.Context
		Bucket string
	}
	mock.lockDeleteBucket.RLock()
	calls = mock.calls.DeleteBucket
	mock.lockDeleteBucket.RUnlock()
	return calls
}

// DeleteObject calls DeleteObjectFunc.
func (mock *ServiceMock) DeleteObject(ctx context.Context, bucket string, key string) error {
	if mock.DeleteObjectFunc == nil {
		panic("ServiceMock.DeleteObjectFunc: method is nil but Service.DeleteObject was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		Bucket string
		Key    string
	}{
		Ctx:    ctx,
		Bucket: bucket,
		Key:    key,
	}
	mock.lockDeleteObject.Lock()
	mock.calls.DeleteObject = append(mock.calls.DeleteObject, callInfo)
	mock.lockDeleteObject.Unlock()
	return mock.DeleteObjectFunc(ctx, bucket, key)
}

// DeleteObjectCalls gets all the calls that were made to DeleteObject.
// Check the length with:
//
//	len(mockedService.DeleteObjectCalls())
func (mock *ServiceMock) DeleteObjectCalls() []struct {
	Ctx    context.Context
	Bucket string
	Key    string
} {
	var calls []struct {
		Ctx    context.Context
		Bucket string
		Key    string
	}
	mock.lockDeleteObject.RLock()
	calls = mock.calls.DeleteObject
	mock.lockDeleteObject.RUnlock()
	return calls
}

// GetObject calls GetObjectFunc.
func (mock *ServiceMock) GetObject(ctx context.Context, bucket string, key string) (*fs.GetObjectResponse, error) {
	if mock.GetObjectFunc == nil {
		panic("ServiceMock.GetObjectFunc: method is nil but Service.GetObject was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		Bucket string
		Key    string
	}{
		Ctx:    ctx,
		Bucket: bucket,
		Key:    key,
	}
	mock.lockGetObject.Lock()
	mock.calls.GetObject = append(mock.calls.GetObject, callInfo)
	mock.lockGetObject.Unlock()
	return mock.GetObjectFunc(ctx, bucket, key)
}

// GetObjectCalls gets all the calls that were made to GetObject.
// Check the length with:
//
//	len(mockedService.GetObjectCalls())
func (mock *ServiceMock) GetObjectCalls() []struct {
	Ctx    context.Context
	Bucket string
	Key    string
} {
	var calls []struct {
		Ctx    context.Context
		Bucket string
		Key    string
	}
	mock.lockGetObject.RLock()
	calls = mock.calls.GetObject
	mock.lockGetObject.RUnlock()
	return calls
}

// ListBuckets calls ListBucketsFunc.
func (mock *ServiceMock) ListBuckets(ctx context.Context) ([]fs.Bucket, error) {
	if mock.ListBucketsFunc == nil {
		panic("ServiceMock.ListBucketsFunc: method is nil but Service.ListBuckets was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockListBuckets.Lock()
	mock.calls.ListBuckets = append(mock.calls.ListBuckets, callInfo)
	mock.lockListBuckets.Unlock()
	return mock.ListBucketsFunc(ctx)
}

// ListBucketsCalls gets all the calls that were made to ListBuckets.
// Check the length with:
//
//	len(mockedService.ListBucketsCalls())
func (mock *ServiceMock) ListBucketsCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockListBuckets.RLock()
	calls = mock.calls.ListBuckets
	mock.lockListBuckets.RUnlock()
	return calls
}

// ListObjects calls ListObjectsFunc.
func (mock *ServiceMock) ListObjects(ctx context.Context, bucket string, prefix string) ([]fs.Object, error) {
	if mock.ListObjectsFunc == nil {
		panic("ServiceMock.ListObjectsFunc: method is nil but Service.ListObjects was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		Bucket string
		Prefix string
	}{
		Ctx:    ctx,
		Bucket: bucket,
		Prefix: prefix,
	}
	mock.lockListObjects.Lock()
	mock.calls.ListObjects = append(mock.calls.ListObjects, callInfo)
	mock.lockListObjects.Unlock()
	return mock.ListObjectsFunc(ctx, bucket, prefix)
}

// ListObjectsCalls gets all the calls that were made to ListObjects.
// Check the length with:
//
//	len(mockedService.ListObjectsCalls())
func (mock *ServiceMock) ListObjectsCalls() []struct {
	Ctx    context.Context
	Bucket string
	Prefix string
} {
	var calls []struct {
		Ctx    context.Context
		Bucket string
		Prefix string
	}
	mock.lockListObjects.RLock()
	calls = mock.calls.ListObjects
	mock.lockListObjects.RUnlock()
	return calls
}

// PutObject calls PutObjectFunc.
func (mock *ServiceMock) PutObject(ctx context.Context, req *fs.PutObjectRequest) error {
	if mock.PutObjectFunc == nil {
		panic("ServiceMock.PutObjectFunc: method is nil but Service.PutObject was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Req *fs.PutObjectRequest
	}{
		Ctx: ctx,
		Req: req,
	}
	mock.lockPutObject.Lock()
	mock.calls.PutObject = append(mock.calls.PutObject, callInfo)
	mock.lockPutObject.Unlock()
	return mock.PutObjectFunc(ctx, req)
}

// PutObjectCalls gets all the calls that were made to PutObject.
// Check the length with:
//
//	len(mockedService.PutObjectCalls())
func (mock *ServiceMock) PutObjectCalls() []struct {
	Ctx context.Context
	Req *fs.PutObjectRequest
} {
	var calls []struct {
		Ctx context.Context
		Req *fs.PutObjectRequest
	}
	mock.lockPutObject.RLock()
	calls = mock.calls.PutObject
	mock.lockPutObject.RUnlock()
	return calls
}

// UploadPart calls UploadPartFunc.
func (mock *ServiceMock) UploadPart(ctx context.Context, req *fs.UploadPartRequest) (*fs.Part, error) {
	if mock.UploadPartFunc == nil {
		panic("ServiceMock.UploadPartFunc: method is nil but Service.UploadPart was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Req *fs.UploadPartRequest
	}{
		Ctx: ctx,
		Req: req,
	}
	mock.lockUploadPart.Lock()
	mock.calls.UploadPart = append(mock.calls.UploadPart, callInfo)
	mock.lockUploadPart.Unlock()
	return mock.UploadPartFunc(ctx, req)
}

// UploadPartCalls gets all the calls that were made to UploadPart.
// Check the length with:
//
//	len(mockedService.UploadPartCalls())
func (mock *ServiceMock) UploadPartCalls() []struct {
	Ctx context.Context
	Req *fs.UploadPartRequest
} {
	var calls []struct {
		Ctx context.Context
		Req *fs.UploadPartRequest
	}
	mock.lockUploadPart.RLock()
	calls = mock.calls.UploadPart
	mock.lockUploadPart.RUnlock()
	return calls
}
