// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mock

import (
	"context"
	"sync"

	"github.com/go-faster/fs"
)

// Ensure, that ServiceMock does implement fs.Service.
// If this is not the case, regenerate this file with moq.
var _ fs.Service = &ServiceMock{}

// ServiceMock is a mock implementation of fs.Service.
//
//	func TestSomethingThatUsesService(t *testing.T) {
//
//		// make and configure a mocked fs.Service
//		mockedService := &ServiceMock{
//			CreateBucketFunc: func(ctx context.Context, bucket string) error {
//				panic("mock out the CreateBucket method")
//			},
//			ListBucketsFunc: func(ctx context.Context) ([]fs.Bucket, error) {
//				panic("mock out the ListBuckets method")
//			},
//			ListObjectsFunc: func(ctx context.Context, bucket string, prefix string) ([]fs.Object, error) {
//				panic("mock out the ListObjects method")
//			},
//			PutObjectFunc: func(ctx context.Context, req *fs.PutObjectRequest) error {
//				panic("mock out the PutObject method")
//			},
//		}
//
//		// use mockedService in code that requires fs.Service
//		// and then make assertions.
//
//	}
type ServiceMock struct {
	// CreateBucketFunc mocks the CreateBucket method.
	CreateBucketFunc func(ctx context.Context, bucket string) error

	// ListBucketsFunc mocks the ListBuckets method.
	ListBucketsFunc func(ctx context.Context) ([]fs.Bucket, error)

	// ListObjectsFunc mocks the ListObjects method.
	ListObjectsFunc func(ctx context.Context, bucket string, prefix string) ([]fs.Object, error)

	// PutObjectFunc mocks the PutObject method.
	PutObjectFunc func(ctx context.Context, req *fs.PutObjectRequest) error

	// calls tracks calls to the methods.
	calls struct {
		// CreateBucket holds details about calls to the CreateBucket method.
		CreateBucket []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Bucket is the bucket argument value.
			Bucket string
		}
		// ListBuckets holds details about calls to the ListBuckets method.
		ListBuckets []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
		// ListObjects holds details about calls to the ListObjects method.
		ListObjects []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Bucket is the bucket argument value.
			Bucket string
			// Prefix is the prefix argument value.
			Prefix string
		}
		// PutObject holds details about calls to the PutObject method.
		PutObject []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Req is the req argument value.
			Req *fs.PutObjectRequest
		}
	}
	lockCreateBucket sync.RWMutex
	lockListBuckets  sync.RWMutex
	lockListObjects  sync.RWMutex
	lockPutObject    sync.RWMutex
}

// CreateBucket calls CreateBucketFunc.
func (mock *ServiceMock) CreateBucket(ctx context.Context, bucket string) error {
	if mock.CreateBucketFunc == nil {
		panic("ServiceMock.CreateBucketFunc: method is nil but Service.CreateBucket was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		Bucket string
	}{
		Ctx:    ctx,
		Bucket: bucket,
	}
	mock.lockCreateBucket.Lock()
	mock.calls.CreateBucket = append(mock.calls.CreateBucket, callInfo)
	mock.lockCreateBucket.Unlock()
	return mock.CreateBucketFunc(ctx, bucket)
}

// CreateBucketCalls gets all the calls that were made to CreateBucket.
// Check the length with:
//
//	len(mockedService.CreateBucketCalls())
func (mock *ServiceMock) CreateBucketCalls() []struct {
	Ctx    context.Context
	Bucket string
} {
	var calls []struct {
		Ctx    context.Context
		Bucket string
	}
	mock.lockCreateBucket.RLock()
	calls = mock.calls.CreateBucket
	mock.lockCreateBucket.RUnlock()
	return calls
}

// ListBuckets calls ListBucketsFunc.
func (mock *ServiceMock) ListBuckets(ctx context.Context) ([]fs.Bucket, error) {
	if mock.ListBucketsFunc == nil {
		panic("ServiceMock.ListBucketsFunc: method is nil but Service.ListBuckets was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockListBuckets.Lock()
	mock.calls.ListBuckets = append(mock.calls.ListBuckets, callInfo)
	mock.lockListBuckets.Unlock()
	return mock.ListBucketsFunc(ctx)
}

// ListBucketsCalls gets all the calls that were made to ListBuckets.
// Check the length with:
//
//	len(mockedService.ListBucketsCalls())
func (mock *ServiceMock) ListBucketsCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockListBuckets.RLock()
	calls = mock.calls.ListBuckets
	mock.lockListBuckets.RUnlock()
	return calls
}

// ListObjects calls ListObjectsFunc.
func (mock *ServiceMock) ListObjects(ctx context.Context, bucket string, prefix string) ([]fs.Object, error) {
	if mock.ListObjectsFunc == nil {
		panic("ServiceMock.ListObjectsFunc: method is nil but Service.ListObjects was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		Bucket string
		Prefix string
	}{
		Ctx:    ctx,
		Bucket: bucket,
		Prefix: prefix,
	}
	mock.lockListObjects.Lock()
	mock.calls.ListObjects = append(mock.calls.ListObjects, callInfo)
	mock.lockListObjects.Unlock()
	return mock.ListObjectsFunc(ctx, bucket, prefix)
}

// ListObjectsCalls gets all the calls that were made to ListObjects.
// Check the length with:
//
//	len(mockedService.ListObjectsCalls())
func (mock *ServiceMock) ListObjectsCalls() []struct {
	Ctx    context.Context
	Bucket string
	Prefix string
} {
	var calls []struct {
		Ctx    context.Context
		Bucket string
		Prefix string
	}
	mock.lockListObjects.RLock()
	calls = mock.calls.ListObjects
	mock.lockListObjects.RUnlock()
	return calls
}

// PutObject calls PutObjectFunc.
func (mock *ServiceMock) PutObject(ctx context.Context, req *fs.PutObjectRequest) error {
	if mock.PutObjectFunc == nil {
		panic("ServiceMock.PutObjectFunc: method is nil but Service.PutObject was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Req *fs.PutObjectRequest
	}{
		Ctx: ctx,
		Req: req,
	}
	mock.lockPutObject.Lock()
	mock.calls.PutObject = append(mock.calls.PutObject, callInfo)
	mock.lockPutObject.Unlock()
	return mock.PutObjectFunc(ctx, req)
}

// PutObjectCalls gets all the calls that were made to PutObject.
// Check the length with:
//
//	len(mockedService.PutObjectCalls())
func (mock *ServiceMock) PutObjectCalls() []struct {
	Ctx context.Context
	Req *fs.PutObjectRequest
} {
	var calls []struct {
		Ctx context.Context
		Req *fs.PutObjectRequest
	}
	mock.lockPutObject.RLock()
	calls = mock.calls.PutObject
	mock.lockPutObject.RUnlock()
	return calls
}
