// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mock

import (
	"context"
	"sync"

	"github.com/go-faster/fs"
)

// Ensure, that StorageMock does implement fs.Storage.
// If this is not the case, regenerate this file with moq.
var _ fs.Storage = &StorageMock{}

// StorageMock is a mock implementation of fs.Storage.
//
//	func TestSomethingThatUsesStorage(t *testing.T) {
//
//		// make and configure a mocked fs.Storage
//		mockedStorage := &StorageMock{
//			CreateBucketFunc: func(ctx context.Context, bucket string) error {
//				panic("mock out the CreateBucket method")
//			},
//			DeleteBucketFunc: func(ctx context.Context, bucket string) error {
//				panic("mock out the DeleteBucket method")
//			},
//			DeleteObjectFunc: func(ctx context.Context, bucket string, key string) error {
//				panic("mock out the DeleteObject method")
//			},
//			ListBucketsFunc: func(ctx context.Context) ([]fs.Bucket, error) {
//				panic("mock out the ListBuckets method")
//			},
//			ListObjectsFunc: func(ctx context.Context, bucket string, prefix string) ([]fs.Object, error) {
//				panic("mock out the ListObjects method")
//			},
//			PutObjectFunc: func(ctx context.Context, req *fs.PutObjectRequest) error {
//				panic("mock out the PutObject method")
//			},
//		}
//
//		// use mockedStorage in code that requires fs.Storage
//		// and then make assertions.
//
//	}
type StorageMock struct {
	// CreateBucketFunc mocks the CreateBucket method.
	CreateBucketFunc func(ctx context.Context, bucket string) error

	// DeleteBucketFunc mocks the DeleteBucket method.
	DeleteBucketFunc func(ctx context.Context, bucket string) error

	// DeleteObjectFunc mocks the DeleteObject method.
	DeleteObjectFunc func(ctx context.Context, bucket string, key string) error

	// ListBucketsFunc mocks the ListBuckets method.
	ListBucketsFunc func(ctx context.Context) ([]fs.Bucket, error)

	// ListObjectsFunc mocks the ListObjects method.
	ListObjectsFunc func(ctx context.Context, bucket string, prefix string) ([]fs.Object, error)

	// PutObjectFunc mocks the PutObject method.
	PutObjectFunc func(ctx context.Context, req *fs.PutObjectRequest) error

	// calls tracks calls to the methods.
	calls struct {
		// CreateBucket holds details about calls to the CreateBucket method.
		CreateBucket []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Bucket is the bucket argument value.
			Bucket string
		}
		// DeleteBucket holds details about calls to the DeleteBucket method.
		DeleteBucket []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Bucket is the bucket argument value.
			Bucket string
		}
		// DeleteObject holds details about calls to the DeleteObject method.
		DeleteObject []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Bucket is the bucket argument value.
			Bucket string
			// Key is the key argument value.
			Key string
		}
		// ListBuckets holds details about calls to the ListBuckets method.
		ListBuckets []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
		// ListObjects holds details about calls to the ListObjects method.
		ListObjects []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Bucket is the bucket argument value.
			Bucket string
			// Prefix is the prefix argument value.
			Prefix string
		}
		// PutObject holds details about calls to the PutObject method.
		PutObject []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Req is the req argument value.
			Req *fs.PutObjectRequest
		}
	}
	lockCreateBucket sync.RWMutex
	lockDeleteBucket sync.RWMutex
	lockDeleteObject sync.RWMutex
	lockListBuckets  sync.RWMutex
	lockListObjects  sync.RWMutex
	lockPutObject    sync.RWMutex
}

// CreateBucket calls CreateBucketFunc.
func (mock *StorageMock) CreateBucket(ctx context.Context, bucket string) error {
	if mock.CreateBucketFunc == nil {
		panic("StorageMock.CreateBucketFunc: method is nil but Storage.CreateBucket was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		Bucket string
	}{
		Ctx:    ctx,
		Bucket: bucket,
	}
	mock.lockCreateBucket.Lock()
	mock.calls.CreateBucket = append(mock.calls.CreateBucket, callInfo)
	mock.lockCreateBucket.Unlock()
	return mock.CreateBucketFunc(ctx, bucket)
}

// CreateBucketCalls gets all the calls that were made to CreateBucket.
// Check the length with:
//
//	len(mockedStorage.CreateBucketCalls())
func (mock *StorageMock) CreateBucketCalls() []struct {
	Ctx    context.Context
	Bucket string
} {
	var calls []struct {
		Ctx    context.Context
		Bucket string
	}
	mock.lockCreateBucket.RLock()
	calls = mock.calls.CreateBucket
	mock.lockCreateBucket.RUnlock()
	return calls
}

// DeleteBucket calls DeleteBucketFunc.
func (mock *StorageMock) DeleteBucket(ctx context.Context, bucket string) error {
	if mock.DeleteBucketFunc == nil {
		panic("StorageMock.DeleteBucketFunc: method is nil but Storage.DeleteBucket was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		Bucket string
	}{
		Ctx:    ctx,
		Bucket: bucket,
	}
	mock.lockDeleteBucket.Lock()
	mock.calls.DeleteBucket = append(mock.calls.DeleteBucket, callInfo)
	mock.lockDeleteBucket.Unlock()
	return mock.DeleteBucketFunc(ctx, bucket)
}

// DeleteBucketCalls gets all the calls that were made to DeleteBucket.
// Check the length with:
//
//	len(mockedStorage.DeleteBucketCalls())
func (mock *StorageMock) DeleteBucketCalls() []struct {
	Ctx    context.Context
	Bucket string
} {
	var calls []struct {
		Ctx    context.Context
		Bucket string
	}
	mock.lockDeleteBucket.RLock()
	calls = mock.calls.DeleteBucket
	mock.lockDeleteBucket.RUnlock()
	return calls
}

// DeleteObject calls DeleteObjectFunc.
func (mock *StorageMock) DeleteObject(ctx context.Context, bucket string, key string) error {
	if mock.DeleteObjectFunc == nil {
		panic("StorageMock.DeleteObjectFunc: method is nil but Storage.DeleteObject was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		Bucket string
		Key    string
	}{
		Ctx:    ctx,
		Bucket: bucket,
		Key:    key,
	}
	mock.lockDeleteObject.Lock()
	mock.calls.DeleteObject = append(mock.calls.DeleteObject, callInfo)
	mock.lockDeleteObject.Unlock()
	return mock.DeleteObjectFunc(ctx, bucket, key)
}

// DeleteObjectCalls gets all the calls that were made to DeleteObject.
// Check the length with:
//
//	len(mockedStorage.DeleteObjectCalls())
func (mock *StorageMock) DeleteObjectCalls() []struct {
	Ctx    context.Context
	Bucket string
	Key    string
} {
	var calls []struct {
		Ctx    context.Context
		Bucket string
		Key    string
	}
	mock.lockDeleteObject.RLock()
	calls = mock.calls.DeleteObject
	mock.lockDeleteObject.RUnlock()
	return calls
}

// ListBuckets calls ListBucketsFunc.
func (mock *StorageMock) ListBuckets(ctx context.Context) ([]fs.Bucket, error) {
	if mock.ListBucketsFunc == nil {
		panic("StorageMock.ListBucketsFunc: method is nil but Storage.ListBuckets was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockListBuckets.Lock()
	mock.calls.ListBuckets = append(mock.calls.ListBuckets, callInfo)
	mock.lockListBuckets.Unlock()
	return mock.ListBucketsFunc(ctx)
}

// ListBucketsCalls gets all the calls that were made to ListBuckets.
// Check the length with:
//
//	len(mockedStorage.ListBucketsCalls())
func (mock *StorageMock) ListBucketsCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockListBuckets.RLock()
	calls = mock.calls.ListBuckets
	mock.lockListBuckets.RUnlock()
	return calls
}

// ListObjects calls ListObjectsFunc.
func (mock *StorageMock) ListObjects(ctx context.Context, bucket string, prefix string) ([]fs.Object, error) {
	if mock.ListObjectsFunc == nil {
		panic("StorageMock.ListObjectsFunc: method is nil but Storage.ListObjects was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		Bucket string
		Prefix string
	}{
		Ctx:    ctx,
		Bucket: bucket,
		Prefix: prefix,
	}
	mock.lockListObjects.Lock()
	mock.calls.ListObjects = append(mock.calls.ListObjects, callInfo)
	mock.lockListObjects.Unlock()
	return mock.ListObjectsFunc(ctx, bucket, prefix)
}

// ListObjectsCalls gets all the calls that were made to ListObjects.
// Check the length with:
//
//	len(mockedStorage.ListObjectsCalls())
func (mock *StorageMock) ListObjectsCalls() []struct {
	Ctx    context.Context
	Bucket string
	Prefix string
} {
	var calls []struct {
		Ctx    context.Context
		Bucket string
		Prefix string
	}
	mock.lockListObjects.RLock()
	calls = mock.calls.ListObjects
	mock.lockListObjects.RUnlock()
	return calls
}

// PutObject calls PutObjectFunc.
func (mock *StorageMock) PutObject(ctx context.Context, req *fs.PutObjectRequest) error {
	if mock.PutObjectFunc == nil {
		panic("StorageMock.PutObjectFunc: method is nil but Storage.PutObject was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Req *fs.PutObjectRequest
	}{
		Ctx: ctx,
		Req: req,
	}
	mock.lockPutObject.Lock()
	mock.calls.PutObject = append(mock.calls.PutObject, callInfo)
	mock.lockPutObject.Unlock()
	return mock.PutObjectFunc(ctx, req)
}

// PutObjectCalls gets all the calls that were made to PutObject.
// Check the length with:
//
//	len(mockedStorage.PutObjectCalls())
func (mock *StorageMock) PutObjectCalls() []struct {
	Ctx context.Context
	Req *fs.PutObjectRequest
} {
	var calls []struct {
		Ctx context.Context
		Req *fs.PutObjectRequest
	}
	mock.lockPutObject.RLock()
	calls = mock.calls.PutObject
	mock.lockPutObject.RUnlock()
	return calls
}
